// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat/v1/chat.proto
// Protobuf Java Version: 4.34.1

package com.chat.v1;

@com.google.protobuf.Generated
public interface CitationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.v1.Citation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 'stock_data', 'news', 'report', 'financial'
   * </pre>
   *
   * <code>string source_type = 1 [json_name = "sourceType"];</code>
   * @return The sourceType.
   */
  java.lang.String getSourceType();
  /**
   * <pre>
   * 'stock_data', 'news', 'report', 'financial'
   * </pre>
   *
   * <code>string source_type = 1 [json_name = "sourceType"];</code>
   * @return The bytes for sourceType.
   */
  com.google.protobuf.ByteString
      getSourceTypeBytes();

  /**
   * <pre>
   * e.g., stock code, report title
   * </pre>
   *
   * <code>string reference = 2 [json_name = "reference"];</code>
   * @return The reference.
   */
  java.lang.String getReference();
  /**
   * <pre>
   * e.g., stock code, report title
   * </pre>
   *
   * <code>string reference = 2 [json_name = "reference"];</code>
   * @return The bytes for reference.
   */
  com.google.protobuf.ByteString
      getReferenceBytes();

  /**
   * <pre>
   * Link to the referenced data
   * </pre>
   *
   * <code>string url = 3 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * Link to the referenced data
   * </pre>
   *
   * <code>string url = 3 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
