apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shorts
spec:
  template:
    spec:
      containers:
      - image: asia.gcr.io/shorted-dev-aba5688f/shorted/shorts:${VERSION}
        env:
        - name: APP_STORE_POSTGRES_ADDRESS
          value: aws-0-ap-southeast-2.pooler.supabase.com:5432
        - name: APP_STORE_POSTGRES_DATABASE
          value: postgres
        - name: APP_STORE_POSTGRES_USERNAME
          value: postgres.xivfykscsdagwsreyqgf
        - name: APP_STORE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest 
              name: APP_STORE_POSTGRES_PASSWORD