// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/housing.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

/**
 * <pre>
 * One lga_series measure for the council, ascending by period.
 * </pre>
 *
 * Protobuf type {@code shorts.v1alpha1.CouncilSeries}
 */
@com.google.protobuf.Generated
public final class CouncilSeries extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shorts.v1alpha1.CouncilSeries)
    CouncilSeriesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CouncilSeries");
  }
  // Use CouncilSeries.newBuilder() to construct.
  private CouncilSeries(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CouncilSeries() {
    measure_ = "";
    unit_ = "";
    frequency_ = "";
    source_ = "";
    sourceLicence_ = "";
    points_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shorts.v1alpha1.HousingProto.internal_static_shorts_v1alpha1_CouncilSeries_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.shorts.v1alpha1.HousingProto.internal_static_shorts_v1alpha1_CouncilSeries_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shorts.v1alpha1.HousingProto.internal_static_shorts_v1alpha1_CouncilSeries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shorts.v1alpha1.CouncilSeries.class, com.shorts.v1alpha1.CouncilSeries.Builder.class);
  }

  public static final int MEASURE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object measure_ = "";
  /**
   * <pre>
   * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
   * </pre>
   *
   * <code>string measure = 1 [json_name = "measure"];</code>
   * @return The measure.
   */
  @java.lang.Override
  public java.lang.String getMeasure() {
    java.lang.Object ref = measure_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      measure_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
   * </pre>
   *
   * <code>string measure = 1 [json_name = "measure"];</code>
   * @return The bytes for measure.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMeasureBytes() {
    java.lang.Object ref = measure_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      measure_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNIT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unit_ = "";
  /**
   * <pre>
   * persons | AUD | count
   * </pre>
   *
   * <code>string unit = 2 [json_name = "unit"];</code>
   * @return The unit.
   */
  @java.lang.Override
  public java.lang.String getUnit() {
    java.lang.Object ref = unit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unit_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * persons | AUD | count
   * </pre>
   *
   * <code>string unit = 2 [json_name = "unit"];</code>
   * @return The bytes for unit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitBytes() {
    java.lang.Object ref = unit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FREQUENCY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object frequency_ = "";
  /**
   * <pre>
   * annual (30 June) | fy | monthly
   * </pre>
   *
   * <code>string frequency = 3 [json_name = "frequency"];</code>
   * @return The frequency.
   */
  @java.lang.Override
  public java.lang.String getFrequency() {
    java.lang.Object ref = frequency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      frequency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * annual (30 June) | fy | monthly
   * </pre>
   *
   * <code>string frequency = 3 [json_name = "frequency"];</code>
   * @return The bytes for frequency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFrequencyBytes() {
    java.lang.Object ref = frequency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      frequency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <code>string source = 4 [json_name = "source"];</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <code>string source = 4 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_LICENCE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceLicence_ = "";
  /**
   * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
   * @return The sourceLicence.
   */
  @java.lang.Override
  public java.lang.String getSourceLicence() {
    java.lang.Object ref = sourceLicence_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceLicence_ = s;
      return s;
    }
  }
  /**
   * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
   * @return The bytes for sourceLicence.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceLicenceBytes() {
    java.lang.Object ref = sourceLicence_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceLicence_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POINTS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.shorts.v1alpha1.CouncilSeriesPoint> points_;
  /**
   * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
   */
  @java.lang.Override
  public java.util.List<com.shorts.v1alpha1.CouncilSeriesPoint> getPointsList() {
    return points_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.shorts.v1alpha1.CouncilSeriesPointOrBuilder> 
      getPointsOrBuilderList() {
    return points_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
   */
  @java.lang.Override
  public int getPointsCount() {
    return points_.size();
  }
  /**
   * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.CouncilSeriesPoint getPoints(int index) {
    return points_.get(index);
  }
  /**
   * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.CouncilSeriesPointOrBuilder getPointsOrBuilder(
      int index) {
    return points_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(measure_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, measure_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, unit_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frequency_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, frequency_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceLicence_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, sourceLicence_);
    }
    for (int i = 0; i < points_.size(); i++) {
      output.writeMessage(6, points_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(measure_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, measure_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, unit_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frequency_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, frequency_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceLicence_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sourceLicence_);
    }

        {
          final int count = points_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(points_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shorts.v1alpha1.CouncilSeries)) {
      return super.equals(obj);
    }
    com.shorts.v1alpha1.CouncilSeries other = (com.shorts.v1alpha1.CouncilSeries) obj;

    if (!getMeasure()
        .equals(other.getMeasure())) return false;
    if (!getUnit()
        .equals(other.getUnit())) return false;
    if (!getFrequency()
        .equals(other.getFrequency())) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getSourceLicence()
        .equals(other.getSourceLicence())) return false;
    if (!getPointsList()
        .equals(other.getPointsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEASURE_FIELD_NUMBER;
    hash = (53 * hash) + getMeasure().hashCode();
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + getUnit().hashCode();
    hash = (37 * hash) + FREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + getFrequency().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + SOURCE_LICENCE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceLicence().hashCode();
    if (getPointsCount() > 0) {
      hash = (37 * hash) + POINTS_FIELD_NUMBER;
      hash = (53 * hash) + getPointsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.shorts.v1alpha1.CouncilSeries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.shorts.v1alpha1.CouncilSeries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.CouncilSeries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shorts.v1alpha1.CouncilSeries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * One lga_series measure for the council, ascending by period.
   * </pre>
   *
   * Protobuf type {@code shorts.v1alpha1.CouncilSeries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shorts.v1alpha1.CouncilSeries)
      com.shorts.v1alpha1.CouncilSeriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shorts.v1alpha1.HousingProto.internal_static_shorts_v1alpha1_CouncilSeries_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shorts.v1alpha1.HousingProto.internal_static_shorts_v1alpha1_CouncilSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shorts.v1alpha1.CouncilSeries.class, com.shorts.v1alpha1.CouncilSeries.Builder.class);
    }

    // Construct using com.shorts.v1alpha1.CouncilSeries.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      measure_ = "";
      unit_ = "";
      frequency_ = "";
      source_ = "";
      sourceLicence_ = "";
      if (pointsBuilder_ == null) {
        points_ = java.util.Collections.emptyList();
      } else {
        points_ = null;
        pointsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shorts.v1alpha1.HousingProto.internal_static_shorts_v1alpha1_CouncilSeries_descriptor;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.CouncilSeries getDefaultInstanceForType() {
      return com.shorts.v1alpha1.CouncilSeries.getDefaultInstance();
    }

    @java.lang.Override
    public com.shorts.v1alpha1.CouncilSeries build() {
      com.shorts.v1alpha1.CouncilSeries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.CouncilSeries buildPartial() {
      com.shorts.v1alpha1.CouncilSeries result = new com.shorts.v1alpha1.CouncilSeries(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.shorts.v1alpha1.CouncilSeries result) {
      if (pointsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          points_ = java.util.Collections.unmodifiableList(points_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.points_ = points_;
      } else {
        result.points_ = pointsBuilder_.build();
      }
    }

    private void buildPartial0(com.shorts.v1alpha1.CouncilSeries result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.measure_ = measure_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.unit_ = unit_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.frequency_ = frequency_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.source_ = source_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sourceLicence_ = sourceLicence_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shorts.v1alpha1.CouncilSeries) {
        return mergeFrom((com.shorts.v1alpha1.CouncilSeries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shorts.v1alpha1.CouncilSeries other) {
      if (other == com.shorts.v1alpha1.CouncilSeries.getDefaultInstance()) return this;
      if (!other.getMeasure().isEmpty()) {
        measure_ = other.measure_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getUnit().isEmpty()) {
        unit_ = other.unit_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getFrequency().isEmpty()) {
        frequency_ = other.frequency_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSourceLicence().isEmpty()) {
        sourceLicence_ = other.sourceLicence_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (pointsBuilder_ == null) {
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          onChanged();
        }
      } else {
        if (!other.points_.isEmpty()) {
          if (pointsBuilder_.isEmpty()) {
            pointsBuilder_.dispose();
            pointsBuilder_ = null;
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000020);
            pointsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPointsFieldBuilder() : null;
          } else {
            pointsBuilder_.addAllMessages(other.points_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              measure_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              unit_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              frequency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              sourceLicence_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.shorts.v1alpha1.CouncilSeriesPoint m =
                  input.readMessage(
                      com.shorts.v1alpha1.CouncilSeriesPoint.parser(),
                      extensionRegistry);
              if (pointsBuilder_ == null) {
                ensurePointsIsMutable();
                points_.add(m);
              } else {
                pointsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object measure_ = "";
    /**
     * <pre>
     * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
     * </pre>
     *
     * <code>string measure = 1 [json_name = "measure"];</code>
     * @return The measure.
     */
    public java.lang.String getMeasure() {
      java.lang.Object ref = measure_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        measure_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
     * </pre>
     *
     * <code>string measure = 1 [json_name = "measure"];</code>
     * @return The bytes for measure.
     */
    public com.google.protobuf.ByteString
        getMeasureBytes() {
      java.lang.Object ref = measure_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        measure_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
     * </pre>
     *
     * <code>string measure = 1 [json_name = "measure"];</code>
     * @param value The measure to set.
     * @return This builder for chaining.
     */
    public Builder setMeasure(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      measure_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
     * </pre>
     *
     * <code>string measure = 1 [json_name = "measure"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMeasure() {
      measure_ = getDefaultInstance().getMeasure();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. 'erp', 'house_median_price', 'dwelling_approvals_total'
     * </pre>
     *
     * <code>string measure = 1 [json_name = "measure"];</code>
     * @param value The bytes for measure to set.
     * @return This builder for chaining.
     */
    public Builder setMeasureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      measure_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object unit_ = "";
    /**
     * <pre>
     * persons | AUD | count
     * </pre>
     *
     * <code>string unit = 2 [json_name = "unit"];</code>
     * @return The unit.
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * persons | AUD | count
     * </pre>
     *
     * <code>string unit = 2 [json_name = "unit"];</code>
     * @return The bytes for unit.
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * persons | AUD | count
     * </pre>
     *
     * <code>string unit = 2 [json_name = "unit"];</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      unit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * persons | AUD | count
     * </pre>
     *
     * <code>string unit = 2 [json_name = "unit"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      unit_ = getDefaultInstance().getUnit();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * persons | AUD | count
     * </pre>
     *
     * <code>string unit = 2 [json_name = "unit"];</code>
     * @param value The bytes for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      unit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object frequency_ = "";
    /**
     * <pre>
     * annual (30 June) | fy | monthly
     * </pre>
     *
     * <code>string frequency = 3 [json_name = "frequency"];</code>
     * @return The frequency.
     */
    public java.lang.String getFrequency() {
      java.lang.Object ref = frequency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        frequency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * annual (30 June) | fy | monthly
     * </pre>
     *
     * <code>string frequency = 3 [json_name = "frequency"];</code>
     * @return The bytes for frequency.
     */
    public com.google.protobuf.ByteString
        getFrequencyBytes() {
      java.lang.Object ref = frequency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        frequency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * annual (30 June) | fy | monthly
     * </pre>
     *
     * <code>string frequency = 3 [json_name = "frequency"];</code>
     * @param value The frequency to set.
     * @return This builder for chaining.
     */
    public Builder setFrequency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      frequency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * annual (30 June) | fy | monthly
     * </pre>
     *
     * <code>string frequency = 3 [json_name = "frequency"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequency() {
      frequency_ = getDefaultInstance().getFrequency();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * annual (30 June) | fy | monthly
     * </pre>
     *
     * <code>string frequency = 3 [json_name = "frequency"];</code>
     * @param value The bytes for frequency to set.
     * @return This builder for chaining.
     */
    public Builder setFrequencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      frequency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <code>string source = 4 [json_name = "source"];</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source = 4 [json_name = "source"];</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source = 4 [json_name = "source"];</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string source = 4 [json_name = "source"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string source = 4 [json_name = "source"];</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object sourceLicence_ = "";
    /**
     * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
     * @return The sourceLicence.
     */
    public java.lang.String getSourceLicence() {
      java.lang.Object ref = sourceLicence_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceLicence_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
     * @return The bytes for sourceLicence.
     */
    public com.google.protobuf.ByteString
        getSourceLicenceBytes() {
      java.lang.Object ref = sourceLicence_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceLicence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
     * @param value The sourceLicence to set.
     * @return This builder for chaining.
     */
    public Builder setSourceLicence(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceLicence_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceLicence() {
      sourceLicence_ = getDefaultInstance().getSourceLicence();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string source_licence = 5 [json_name = "sourceLicence"];</code>
     * @param value The bytes for sourceLicence to set.
     * @return This builder for chaining.
     */
    public Builder setSourceLicenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceLicence_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.util.List<com.shorts.v1alpha1.CouncilSeriesPoint> points_ =
      java.util.Collections.emptyList();
    private void ensurePointsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        points_ = new java.util.ArrayList<com.shorts.v1alpha1.CouncilSeriesPoint>(points_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.CouncilSeriesPoint, com.shorts.v1alpha1.CouncilSeriesPoint.Builder, com.shorts.v1alpha1.CouncilSeriesPointOrBuilder> pointsBuilder_;

    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.CouncilSeriesPoint> getPointsList() {
      if (pointsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(points_);
      } else {
        return pointsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public int getPointsCount() {
      if (pointsBuilder_ == null) {
        return points_.size();
      } else {
        return pointsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public com.shorts.v1alpha1.CouncilSeriesPoint getPoints(int index) {
      if (pointsBuilder_ == null) {
        return points_.get(index);
      } else {
        return pointsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder setPoints(
        int index, com.shorts.v1alpha1.CouncilSeriesPoint value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.set(index, value);
        onChanged();
      } else {
        pointsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder setPoints(
        int index, com.shorts.v1alpha1.CouncilSeriesPoint.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.set(index, builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder addPoints(com.shorts.v1alpha1.CouncilSeriesPoint value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(value);
        onChanged();
      } else {
        pointsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder addPoints(
        int index, com.shorts.v1alpha1.CouncilSeriesPoint value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(index, value);
        onChanged();
      } else {
        pointsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder addPoints(
        com.shorts.v1alpha1.CouncilSeriesPoint.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.add(builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder addPoints(
        int index, com.shorts.v1alpha1.CouncilSeriesPoint.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.add(index, builderForValue.build());
        onChanged();
      } else {
        pointsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder addAllPoints(
        java.lang.Iterable<? extends com.shorts.v1alpha1.CouncilSeriesPoint> values) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, points_);
        onChanged();
      } else {
        pointsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder clearPoints() {
      if (pointsBuilder_ == null) {
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        pointsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public Builder removePoints(int index) {
      if (pointsBuilder_ == null) {
        ensurePointsIsMutable();
        points_.remove(index);
        onChanged();
      } else {
        pointsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public com.shorts.v1alpha1.CouncilSeriesPoint.Builder getPointsBuilder(
        int index) {
      return internalGetPointsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public com.shorts.v1alpha1.CouncilSeriesPointOrBuilder getPointsOrBuilder(
        int index) {
      if (pointsBuilder_ == null) {
        return points_.get(index);  } else {
        return pointsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public java.util.List<? extends com.shorts.v1alpha1.CouncilSeriesPointOrBuilder> 
         getPointsOrBuilderList() {
      if (pointsBuilder_ != null) {
        return pointsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(points_);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public com.shorts.v1alpha1.CouncilSeriesPoint.Builder addPointsBuilder() {
      return internalGetPointsFieldBuilder().addBuilder(
          com.shorts.v1alpha1.CouncilSeriesPoint.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public com.shorts.v1alpha1.CouncilSeriesPoint.Builder addPointsBuilder(
        int index) {
      return internalGetPointsFieldBuilder().addBuilder(
          index, com.shorts.v1alpha1.CouncilSeriesPoint.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.CouncilSeriesPoint points = 6 [json_name = "points"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.CouncilSeriesPoint.Builder> 
         getPointsBuilderList() {
      return internalGetPointsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.CouncilSeriesPoint, com.shorts.v1alpha1.CouncilSeriesPoint.Builder, com.shorts.v1alpha1.CouncilSeriesPointOrBuilder> 
        internalGetPointsFieldBuilder() {
      if (pointsBuilder_ == null) {
        pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.shorts.v1alpha1.CouncilSeriesPoint, com.shorts.v1alpha1.CouncilSeriesPoint.Builder, com.shorts.v1alpha1.CouncilSeriesPointOrBuilder>(
                points_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        points_ = null;
      }
      return pointsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:shorts.v1alpha1.CouncilSeries)
  }

  // @@protoc_insertion_point(class_scope:shorts.v1alpha1.CouncilSeries)
  private static final com.shorts.v1alpha1.CouncilSeries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shorts.v1alpha1.CouncilSeries();
  }

  public static com.shorts.v1alpha1.CouncilSeries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CouncilSeries>
      PARSER = new com.google.protobuf.AbstractParser<CouncilSeries>() {
    @java.lang.Override
    public CouncilSeries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CouncilSeries> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CouncilSeries> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shorts.v1alpha1.CouncilSeries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

