// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/politicians.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public interface DeclaredInterestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shorts.v1alpha1.DeclaredInterest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1 shareholdings, 3 real estate, 4 directorships…
   * </pre>
   *
   * <code>int32 item_no = 1 [json_name = "itemNo"];</code>
   * @return The itemNo.
   */
  int getItemNo();

  /**
   * <code>string item_label = 2 [json_name = "itemLabel"];</code>
   * @return The itemLabel.
   */
  java.lang.String getItemLabel();
  /**
   * <code>string item_label = 2 [json_name = "itemLabel"];</code>
   * @return The bytes for itemLabel.
   */
  com.google.protobuf.ByteString
      getItemLabelBytes();

  /**
   * <code>.shorts.v1alpha1.RegisterHolder holder = 3 [json_name = "holder"];</code>
   * @return The enum numeric value on the wire for holder.
   */
  int getHolderValue();
  /**
   * <code>.shorts.v1alpha1.RegisterHolder holder = 3 [json_name = "holder"];</code>
   * @return The holder.
   */
  com.shorts.v1alpha1.RegisterHolder getHolder();

  /**
   * <pre>
   * verbatim, as the member wrote it
   * </pre>
   *
   * <code>string declared_text = 4 [json_name = "declaredText"];</code>
   * @return The declaredText.
   */
  java.lang.String getDeclaredText();
  /**
   * <pre>
   * verbatim, as the member wrote it
   * </pre>
   *
   * <code>string declared_text = 4 [json_name = "declaredText"];</code>
   * @return The bytes for declaredText.
   */
  com.google.protobuf.ByteString
      getDeclaredTextBytes();

  /**
   * <pre>
   * item 3 purpose, item 6 creditor…
   * </pre>
   *
   * <code>string secondary_text = 5 [json_name = "secondaryText"];</code>
   * @return The secondaryText.
   */
  java.lang.String getSecondaryText();
  /**
   * <pre>
   * item 3 purpose, item 6 creditor…
   * </pre>
   *
   * <code>string secondary_text = 5 [json_name = "secondaryText"];</code>
   * @return The bytes for secondaryText.
   */
  com.google.protobuf.ByteString
      getSecondaryTextBytes();

  /**
   * <pre>
   * empty unless publishably resolved
   * </pre>
   *
   * <code>string stock_code = 6 [json_name = "stockCode"];</code>
   * @return The stockCode.
   */
  java.lang.String getStockCode();
  /**
   * <pre>
   * empty unless publishably resolved
   * </pre>
   *
   * <code>string stock_code = 6 [json_name = "stockCode"];</code>
   * @return The bytes for stockCode.
   */
  com.google.protobuf.ByteString
      getStockCodeBytes();

  /**
   * <code>string company_name = 7 [json_name = "companyName"];</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 7 [json_name = "companyName"];</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string industry = 8 [json_name = "industry"];</code>
   * @return The industry.
   */
  java.lang.String getIndustry();
  /**
   * <code>string industry = 8 [json_name = "industry"];</code>
   * @return The bytes for industry.
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <pre>
   * empty unless resolved to an ABS suburb
   * </pre>
   *
   * <code>string sal_code = 9 [json_name = "salCode"];</code>
   * @return The salCode.
   */
  java.lang.String getSalCode();
  /**
   * <pre>
   * empty unless resolved to an ABS suburb
   * </pre>
   *
   * <code>string sal_code = 9 [json_name = "salCode"];</code>
   * @return The bytes for salCode.
   */
  com.google.protobuf.ByteString
      getSalCodeBytes();

  /**
   * <code>string suburb_name = 10 [json_name = "suburbName"];</code>
   * @return The suburbName.
   */
  java.lang.String getSuburbName();
  /**
   * <code>string suburb_name = 10 [json_name = "suburbName"];</code>
   * @return The bytes for suburbName.
   */
  com.google.protobuf.ByteString
      getSuburbNameBytes();

  /**
   * <code>string property_state = 11 [json_name = "propertyState"];</code>
   * @return The propertyState.
   */
  java.lang.String getPropertyState();
  /**
   * <code>string property_state = 11 [json_name = "propertyState"];</code>
   * @return The bytes for propertyState.
   */
  com.google.protobuf.ByteString
      getPropertyStateBytes();

  /**
   * <pre>
   * curated_alias | ticker_in_text | name_exact
   * </pre>
   *
   * <code>string match_method = 12 [json_name = "matchMethod"];</code>
   * @return The matchMethod.
   */
  java.lang.String getMatchMethod();
  /**
   * <pre>
   * curated_alias | ticker_in_text | name_exact
   * </pre>
   *
   * <code>string match_method = 12 [json_name = "matchMethod"];</code>
   * @return The bytes for matchMethod.
   */
  com.google.protobuf.ByteString
      getMatchMethodBytes();

  /**
   * <code>.google.protobuf.Timestamp declared_from = 13 [json_name = "declaredFrom"];</code>
   * @return Whether the declaredFrom field is set.
   */
  boolean hasDeclaredFrom();
  /**
   * <code>.google.protobuf.Timestamp declared_from = 13 [json_name = "declaredFrom"];</code>
   * @return The declaredFrom.
   */
  com.google.protobuf.Timestamp getDeclaredFrom();
  /**
   * <code>.google.protobuf.Timestamp declared_from = 13 [json_name = "declaredFrom"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeclaredFromOrBuilder();

  /**
   * <code>bool declared_from_known = 14 [json_name = "declaredFromKnown"];</code>
   * @return The declaredFromKnown.
   */
  boolean getDeclaredFromKnown();

  /**
   * <pre>
   * absent while still declared
   * </pre>
   *
   * <code>.google.protobuf.Timestamp declared_to = 15 [json_name = "declaredTo"];</code>
   * @return Whether the declaredTo field is set.
   */
  boolean hasDeclaredTo();
  /**
   * <pre>
   * absent while still declared
   * </pre>
   *
   * <code>.google.protobuf.Timestamp declared_to = 15 [json_name = "declaredTo"];</code>
   * @return The declaredTo.
   */
  com.google.protobuf.Timestamp getDeclaredTo();
  /**
   * <pre>
   * absent while still declared
   * </pre>
   *
   * <code>.google.protobuf.Timestamp declared_to = 15 [json_name = "declaredTo"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeclaredToOrBuilder();

  /**
   * <code>bool currently_declared = 16 [json_name = "currentlyDeclared"];</code>
   * @return The currentlyDeclared.
   */
  boolean getCurrentlyDeclared();

  /**
   * <pre>
   * the aph.gov.au PDF this came from
   * </pre>
   *
   * <code>string source_url = 17 [json_name = "sourceUrl"];</code>
   * @return The sourceUrl.
   */
  java.lang.String getSourceUrl();
  /**
   * <pre>
   * the aph.gov.au PDF this came from
   * </pre>
   *
   * <code>string source_url = 17 [json_name = "sourceUrl"];</code>
   * @return The bytes for sourceUrl.
   */
  com.google.protobuf.ByteString
      getSourceUrlBytes();

  /**
   * <code>string source_licence = 18 [json_name = "sourceLicence"];</code>
   * @return The sourceLicence.
   */
  java.lang.String getSourceLicence();
  /**
   * <code>string source_licence = 18 [json_name = "sourceLicence"];</code>
   * @return The bytes for sourceLicence.
   */
  com.google.protobuf.ByteString
      getSourceLicenceBytes();

  /**
   * <pre>
   * What the declared entity IS: listed | private_company | family_trust |
   * smsf | managed_fund | foreign | not_an_entity.
   *
   * A consumer needs this to describe an unmatched row honestly. "Not matched to
   * an ASX listing" is only true of entity_kind='listed'; saying it about a
   * family trust reports a system failure that did not happen, because a trust
   * can never have a ticker.
   * </pre>
   *
   * <code>string entity_kind = 19 [json_name = "entityKind"];</code>
   * @return The entityKind.
   */
  java.lang.String getEntityKind();
  /**
   * <pre>
   * What the declared entity IS: listed | private_company | family_trust |
   * smsf | managed_fund | foreign | not_an_entity.
   *
   * A consumer needs this to describe an unmatched row honestly. "Not matched to
   * an ASX listing" is only true of entity_kind='listed'; saying it about a
   * family trust reports a system failure that did not happen, because a trust
   * can never have a ticker.
   * </pre>
   *
   * <code>string entity_kind = 19 [json_name = "entityKind"];</code>
   * @return The bytes for entityKind.
   */
  com.google.protobuf.ByteString
      getEntityKindBytes();
}
