// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/shorts.proto
// Protobuf Java Version: 4.34.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public interface GetDirectorTradesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shorts.v1alpha1.GetDirectorTradesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ASX stock code
   * </pre>
   *
   * <code>string stock_code = 1 [json_name = "stockCode"];</code>
   * @return The stockCode.
   */
  java.lang.String getStockCode();
  /**
   * <pre>
   * ASX stock code
   * </pre>
   *
   * <code>string stock_code = 1 [json_name = "stockCode"];</code>
   * @return The bytes for stockCode.
   */
  com.google.protobuf.ByteString
      getStockCodeBytes();

  /**
   * <pre>
   * Max trades to return (default 20)
   * </pre>
   *
   * <code>int32 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();
}
