// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/shorts.proto
// Protobuf Java Version: 4.33.5

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public interface GetTopStocksForEnrichmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shorts.v1alpha1.GetTopStocksForEnrichmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .shorts.v1alpha1.StockEnrichmentCandidate stocks = 1 [json_name = "stocks"];</code>
   */
  java.util.List<com.shorts.v1alpha1.StockEnrichmentCandidate> 
      getStocksList();
  /**
   * <code>repeated .shorts.v1alpha1.StockEnrichmentCandidate stocks = 1 [json_name = "stocks"];</code>
   */
  com.shorts.v1alpha1.StockEnrichmentCandidate getStocks(int index);
  /**
   * <code>repeated .shorts.v1alpha1.StockEnrichmentCandidate stocks = 1 [json_name = "stocks"];</code>
   */
  int getStocksCount();
  /**
   * <code>repeated .shorts.v1alpha1.StockEnrichmentCandidate stocks = 1 [json_name = "stocks"];</code>
   */
  java.util.List<? extends com.shorts.v1alpha1.StockEnrichmentCandidateOrBuilder> 
      getStocksOrBuilderList();
  /**
   * <code>repeated .shorts.v1alpha1.StockEnrichmentCandidate stocks = 1 [json_name = "stocks"];</code>
   */
  com.shorts.v1alpha1.StockEnrichmentCandidateOrBuilder getStocksOrBuilder(
      int index);
}
