// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/market.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public interface IndexPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shorts.v1alpha1.IndexPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * YYYY-MM-DD.
   * </pre>
   *
   * <code>string date = 1 [json_name = "date"];</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <pre>
   * YYYY-MM-DD.
   * </pre>
   *
   * <code>string date = 1 [json_name = "date"];</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>double open = 2 [json_name = "open"];</code>
   * @return The open.
   */
  double getOpen();

  /**
   * <code>double high = 3 [json_name = "high"];</code>
   * @return The high.
   */
  double getHigh();

  /**
   * <code>double low = 4 [json_name = "low"];</code>
   * @return The low.
   */
  double getLow();

  /**
   * <pre>
   * The index level. Compute returns from this.
   * </pre>
   *
   * <code>double close = 5 [json_name = "close"];</code>
   * @return The close.
   */
  double getClose();

  /**
   * <pre>
   * Often 0: an index level has no meaningful traded volume.
   * </pre>
   *
   * <code>int64 volume = 6 [json_name = "volume"];</code>
   * @return The volume.
   */
  long getVolume();
}
