// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/stock.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

/**
 * <pre>
 * The company filing behind the latest reported period, with its summary.
 * </pre>
 *
 * Protobuf type {@code shorts.v1alpha1.LatestFilingSummary}
 */
@com.google.protobuf.Generated
public final class LatestFilingSummary extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shorts.v1alpha1.LatestFilingSummary)
    LatestFilingSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "LatestFilingSummary");
  }
  // Use LatestFilingSummary.newBuilder() to construct.
  private LatestFilingSummary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LatestFilingSummary() {
    reportUrl_ = "";
    reportTitle_ = "";
    reportDate_ = "";
    periodEnd_ = "";
    periodType_ = "";
    digest_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shorts.v1alpha1.StockProto.internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.shorts.v1alpha1.StockProto.internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shorts.v1alpha1.StockProto.internal_static_shorts_v1alpha1_LatestFilingSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shorts.v1alpha1.LatestFilingSummary.class, com.shorts.v1alpha1.LatestFilingSummary.Builder.class);
  }

  public static final int REPORT_URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportUrl_ = "";
  /**
   * <code>string report_url = 1 [json_name = "reportUrl"];</code>
   * @return The reportUrl.
   */
  @java.lang.Override
  public java.lang.String getReportUrl() {
    java.lang.Object ref = reportUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string report_url = 1 [json_name = "reportUrl"];</code>
   * @return The bytes for reportUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportUrlBytes() {
    java.lang.Object ref = reportUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORT_TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportTitle_ = "";
  /**
   * <code>string report_title = 2 [json_name = "reportTitle"];</code>
   * @return The reportTitle.
   */
  @java.lang.Override
  public java.lang.String getReportTitle() {
    java.lang.Object ref = reportTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string report_title = 2 [json_name = "reportTitle"];</code>
   * @return The bytes for reportTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportTitleBytes() {
    java.lang.Object ref = reportTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORT_DATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportDate_ = "";
  /**
   * <pre>
   * YYYY-MM-DD.
   * </pre>
   *
   * <code>string report_date = 3 [json_name = "reportDate"];</code>
   * @return The reportDate.
   */
  @java.lang.Override
  public java.lang.String getReportDate() {
    java.lang.Object ref = reportDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportDate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * YYYY-MM-DD.
   * </pre>
   *
   * <code>string report_date = 3 [json_name = "reportDate"];</code>
   * @return The bytes for reportDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportDateBytes() {
    java.lang.Object ref = reportDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERIOD_END_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object periodEnd_ = "";
  /**
   * <pre>
   * YYYY-MM-DD, the period the filing reports.
   * </pre>
   *
   * <code>string period_end = 4 [json_name = "periodEnd"];</code>
   * @return The periodEnd.
   */
  @java.lang.Override
  public java.lang.String getPeriodEnd() {
    java.lang.Object ref = periodEnd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      periodEnd_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * YYYY-MM-DD, the period the filing reports.
   * </pre>
   *
   * <code>string period_end = 4 [json_name = "periodEnd"];</code>
   * @return The bytes for periodEnd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeriodEndBytes() {
    java.lang.Object ref = periodEnd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      periodEnd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERIOD_TYPE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object periodType_ = "";
  /**
   * <pre>
   * "annual" | "half".
   * </pre>
   *
   * <code>string period_type = 5 [json_name = "periodType"];</code>
   * @return The periodType.
   */
  @java.lang.Override
  public java.lang.String getPeriodType() {
    java.lang.Object ref = periodType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      periodType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "annual" | "half".
   * </pre>
   *
   * <code>string period_type = 5 [json_name = "periodType"];</code>
   * @return The bytes for periodType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeriodTypeBytes() {
    java.lang.Object ref = periodType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      periodType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIGEST_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object digest_ = "";
  /**
   * <pre>
   * Short summary of the filing.
   * </pre>
   *
   * <code>string digest = 6 [json_name = "digest"];</code>
   * @return The digest.
   */
  @java.lang.Override
  public java.lang.String getDigest() {
    java.lang.Object ref = digest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      digest_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Short summary of the filing.
   * </pre>
   *
   * <code>string digest = 6 [json_name = "digest"];</code>
   * @return The bytes for digest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDigestBytes() {
    java.lang.Object ref = digest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      digest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIGEST_CONFIDENCE_FIELD_NUMBER = 7;
  private double digestConfidence_ = 0D;
  /**
   * <pre>
   * 0-1.
   * </pre>
   *
   * <code>double digest_confidence = 7 [json_name = "digestConfidence"];</code>
   * @return The digestConfidence.
   */
  @java.lang.Override
  public double getDigestConfidence() {
    return digestConfidence_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reportUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, reportUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reportTitle_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, reportTitle_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reportDate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, reportDate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(periodEnd_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, periodEnd_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(periodType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, periodType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(digest_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, digest_);
    }
    if (java.lang.Double.doubleToRawLongBits(digestConfidence_) != 0) {
      output.writeDouble(7, digestConfidence_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reportUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reportUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reportTitle_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, reportTitle_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reportDate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, reportDate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(periodEnd_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, periodEnd_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(periodType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, periodType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(digest_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, digest_);
    }
    if (java.lang.Double.doubleToRawLongBits(digestConfidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, digestConfidence_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shorts.v1alpha1.LatestFilingSummary)) {
      return super.equals(obj);
    }
    com.shorts.v1alpha1.LatestFilingSummary other = (com.shorts.v1alpha1.LatestFilingSummary) obj;

    if (!getReportUrl()
        .equals(other.getReportUrl())) return false;
    if (!getReportTitle()
        .equals(other.getReportTitle())) return false;
    if (!getReportDate()
        .equals(other.getReportDate())) return false;
    if (!getPeriodEnd()
        .equals(other.getPeriodEnd())) return false;
    if (!getPeriodType()
        .equals(other.getPeriodType())) return false;
    if (!getDigest()
        .equals(other.getDigest())) return false;
    if (java.lang.Double.doubleToLongBits(getDigestConfidence())
        != java.lang.Double.doubleToLongBits(
            other.getDigestConfidence())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPORT_URL_FIELD_NUMBER;
    hash = (53 * hash) + getReportUrl().hashCode();
    hash = (37 * hash) + REPORT_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getReportTitle().hashCode();
    hash = (37 * hash) + REPORT_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getReportDate().hashCode();
    hash = (37 * hash) + PERIOD_END_FIELD_NUMBER;
    hash = (53 * hash) + getPeriodEnd().hashCode();
    hash = (37 * hash) + PERIOD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPeriodType().hashCode();
    hash = (37 * hash) + DIGEST_FIELD_NUMBER;
    hash = (53 * hash) + getDigest().hashCode();
    hash = (37 * hash) + DIGEST_CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDigestConfidence()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.shorts.v1alpha1.LatestFilingSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.shorts.v1alpha1.LatestFilingSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.LatestFilingSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shorts.v1alpha1.LatestFilingSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The company filing behind the latest reported period, with its summary.
   * </pre>
   *
   * Protobuf type {@code shorts.v1alpha1.LatestFilingSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shorts.v1alpha1.LatestFilingSummary)
      com.shorts.v1alpha1.LatestFilingSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shorts.v1alpha1.StockProto.internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shorts.v1alpha1.StockProto.internal_static_shorts_v1alpha1_LatestFilingSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shorts.v1alpha1.LatestFilingSummary.class, com.shorts.v1alpha1.LatestFilingSummary.Builder.class);
    }

    // Construct using com.shorts.v1alpha1.LatestFilingSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reportUrl_ = "";
      reportTitle_ = "";
      reportDate_ = "";
      periodEnd_ = "";
      periodType_ = "";
      digest_ = "";
      digestConfidence_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shorts.v1alpha1.StockProto.internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.LatestFilingSummary getDefaultInstanceForType() {
      return com.shorts.v1alpha1.LatestFilingSummary.getDefaultInstance();
    }

    @java.lang.Override
    public com.shorts.v1alpha1.LatestFilingSummary build() {
      com.shorts.v1alpha1.LatestFilingSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.LatestFilingSummary buildPartial() {
      com.shorts.v1alpha1.LatestFilingSummary result = new com.shorts.v1alpha1.LatestFilingSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.shorts.v1alpha1.LatestFilingSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reportUrl_ = reportUrl_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reportTitle_ = reportTitle_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reportDate_ = reportDate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.periodEnd_ = periodEnd_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.periodType_ = periodType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.digest_ = digest_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.digestConfidence_ = digestConfidence_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shorts.v1alpha1.LatestFilingSummary) {
        return mergeFrom((com.shorts.v1alpha1.LatestFilingSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shorts.v1alpha1.LatestFilingSummary other) {
      if (other == com.shorts.v1alpha1.LatestFilingSummary.getDefaultInstance()) return this;
      if (!other.getReportUrl().isEmpty()) {
        reportUrl_ = other.reportUrl_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getReportTitle().isEmpty()) {
        reportTitle_ = other.reportTitle_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getReportDate().isEmpty()) {
        reportDate_ = other.reportDate_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPeriodEnd().isEmpty()) {
        periodEnd_ = other.periodEnd_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPeriodType().isEmpty()) {
        periodType_ = other.periodType_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getDigest().isEmpty()) {
        digest_ = other.digest_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getDigestConfidence()) != 0) {
        setDigestConfidence(other.getDigestConfidence());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              reportUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              reportTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              reportDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              periodEnd_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              periodType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              digest_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 57: {
              digestConfidence_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object reportUrl_ = "";
    /**
     * <code>string report_url = 1 [json_name = "reportUrl"];</code>
     * @return The reportUrl.
     */
    public java.lang.String getReportUrl() {
      java.lang.Object ref = reportUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string report_url = 1 [json_name = "reportUrl"];</code>
     * @return The bytes for reportUrl.
     */
    public com.google.protobuf.ByteString
        getReportUrlBytes() {
      java.lang.Object ref = reportUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string report_url = 1 [json_name = "reportUrl"];</code>
     * @param value The reportUrl to set.
     * @return This builder for chaining.
     */
    public Builder setReportUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportUrl_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string report_url = 1 [json_name = "reportUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReportUrl() {
      reportUrl_ = getDefaultInstance().getReportUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string report_url = 1 [json_name = "reportUrl"];</code>
     * @param value The bytes for reportUrl to set.
     * @return This builder for chaining.
     */
    public Builder setReportUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportUrl_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object reportTitle_ = "";
    /**
     * <code>string report_title = 2 [json_name = "reportTitle"];</code>
     * @return The reportTitle.
     */
    public java.lang.String getReportTitle() {
      java.lang.Object ref = reportTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string report_title = 2 [json_name = "reportTitle"];</code>
     * @return The bytes for reportTitle.
     */
    public com.google.protobuf.ByteString
        getReportTitleBytes() {
      java.lang.Object ref = reportTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string report_title = 2 [json_name = "reportTitle"];</code>
     * @param value The reportTitle to set.
     * @return This builder for chaining.
     */
    public Builder setReportTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportTitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string report_title = 2 [json_name = "reportTitle"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReportTitle() {
      reportTitle_ = getDefaultInstance().getReportTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string report_title = 2 [json_name = "reportTitle"];</code>
     * @param value The bytes for reportTitle to set.
     * @return This builder for chaining.
     */
    public Builder setReportTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportTitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object reportDate_ = "";
    /**
     * <pre>
     * YYYY-MM-DD.
     * </pre>
     *
     * <code>string report_date = 3 [json_name = "reportDate"];</code>
     * @return The reportDate.
     */
    public java.lang.String getReportDate() {
      java.lang.Object ref = reportDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * YYYY-MM-DD.
     * </pre>
     *
     * <code>string report_date = 3 [json_name = "reportDate"];</code>
     * @return The bytes for reportDate.
     */
    public com.google.protobuf.ByteString
        getReportDateBytes() {
      java.lang.Object ref = reportDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * YYYY-MM-DD.
     * </pre>
     *
     * <code>string report_date = 3 [json_name = "reportDate"];</code>
     * @param value The reportDate to set.
     * @return This builder for chaining.
     */
    public Builder setReportDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * YYYY-MM-DD.
     * </pre>
     *
     * <code>string report_date = 3 [json_name = "reportDate"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReportDate() {
      reportDate_ = getDefaultInstance().getReportDate();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * YYYY-MM-DD.
     * </pre>
     *
     * <code>string report_date = 3 [json_name = "reportDate"];</code>
     * @param value The bytes for reportDate to set.
     * @return This builder for chaining.
     */
    public Builder setReportDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object periodEnd_ = "";
    /**
     * <pre>
     * YYYY-MM-DD, the period the filing reports.
     * </pre>
     *
     * <code>string period_end = 4 [json_name = "periodEnd"];</code>
     * @return The periodEnd.
     */
    public java.lang.String getPeriodEnd() {
      java.lang.Object ref = periodEnd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        periodEnd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * YYYY-MM-DD, the period the filing reports.
     * </pre>
     *
     * <code>string period_end = 4 [json_name = "periodEnd"];</code>
     * @return The bytes for periodEnd.
     */
    public com.google.protobuf.ByteString
        getPeriodEndBytes() {
      java.lang.Object ref = periodEnd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        periodEnd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * YYYY-MM-DD, the period the filing reports.
     * </pre>
     *
     * <code>string period_end = 4 [json_name = "periodEnd"];</code>
     * @param value The periodEnd to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodEnd(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      periodEnd_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * YYYY-MM-DD, the period the filing reports.
     * </pre>
     *
     * <code>string period_end = 4 [json_name = "periodEnd"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriodEnd() {
      periodEnd_ = getDefaultInstance().getPeriodEnd();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * YYYY-MM-DD, the period the filing reports.
     * </pre>
     *
     * <code>string period_end = 4 [json_name = "periodEnd"];</code>
     * @param value The bytes for periodEnd to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodEndBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      periodEnd_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object periodType_ = "";
    /**
     * <pre>
     * "annual" | "half".
     * </pre>
     *
     * <code>string period_type = 5 [json_name = "periodType"];</code>
     * @return The periodType.
     */
    public java.lang.String getPeriodType() {
      java.lang.Object ref = periodType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        periodType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "annual" | "half".
     * </pre>
     *
     * <code>string period_type = 5 [json_name = "periodType"];</code>
     * @return The bytes for periodType.
     */
    public com.google.protobuf.ByteString
        getPeriodTypeBytes() {
      java.lang.Object ref = periodType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        periodType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "annual" | "half".
     * </pre>
     *
     * <code>string period_type = 5 [json_name = "periodType"];</code>
     * @param value The periodType to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      periodType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "annual" | "half".
     * </pre>
     *
     * <code>string period_type = 5 [json_name = "periodType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriodType() {
      periodType_ = getDefaultInstance().getPeriodType();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "annual" | "half".
     * </pre>
     *
     * <code>string period_type = 5 [json_name = "periodType"];</code>
     * @param value The bytes for periodType to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      periodType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object digest_ = "";
    /**
     * <pre>
     * Short summary of the filing.
     * </pre>
     *
     * <code>string digest = 6 [json_name = "digest"];</code>
     * @return The digest.
     */
    public java.lang.String getDigest() {
      java.lang.Object ref = digest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Short summary of the filing.
     * </pre>
     *
     * <code>string digest = 6 [json_name = "digest"];</code>
     * @return The bytes for digest.
     */
    public com.google.protobuf.ByteString
        getDigestBytes() {
      java.lang.Object ref = digest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Short summary of the filing.
     * </pre>
     *
     * <code>string digest = 6 [json_name = "digest"];</code>
     * @param value The digest to set.
     * @return This builder for chaining.
     */
    public Builder setDigest(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      digest_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Short summary of the filing.
     * </pre>
     *
     * <code>string digest = 6 [json_name = "digest"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDigest() {
      digest_ = getDefaultInstance().getDigest();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Short summary of the filing.
     * </pre>
     *
     * <code>string digest = 6 [json_name = "digest"];</code>
     * @param value The bytes for digest to set.
     * @return This builder for chaining.
     */
    public Builder setDigestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      digest_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private double digestConfidence_ ;
    /**
     * <pre>
     * 0-1.
     * </pre>
     *
     * <code>double digest_confidence = 7 [json_name = "digestConfidence"];</code>
     * @return The digestConfidence.
     */
    @java.lang.Override
    public double getDigestConfidence() {
      return digestConfidence_;
    }
    /**
     * <pre>
     * 0-1.
     * </pre>
     *
     * <code>double digest_confidence = 7 [json_name = "digestConfidence"];</code>
     * @param value The digestConfidence to set.
     * @return This builder for chaining.
     */
    public Builder setDigestConfidence(double value) {

      digestConfidence_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-1.
     * </pre>
     *
     * <code>double digest_confidence = 7 [json_name = "digestConfidence"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDigestConfidence() {
      bitField0_ = (bitField0_ & ~0x00000040);
      digestConfidence_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:shorts.v1alpha1.LatestFilingSummary)
  }

  // @@protoc_insertion_point(class_scope:shorts.v1alpha1.LatestFilingSummary)
  private static final com.shorts.v1alpha1.LatestFilingSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shorts.v1alpha1.LatestFilingSummary();
  }

  public static com.shorts.v1alpha1.LatestFilingSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LatestFilingSummary>
      PARSER = new com.google.protobuf.AbstractParser<LatestFilingSummary>() {
    @java.lang.Override
    public LatestFilingSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LatestFilingSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LatestFilingSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shorts.v1alpha1.LatestFilingSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

