// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/politicians.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public interface ListSuburbPoliticiansResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shorts.v1alpha1.ListSuburbPoliticiansResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sal_code = 1 [json_name = "salCode"];</code>
   * @return The salCode.
   */
  java.lang.String getSalCode();
  /**
   * <code>string sal_code = 1 [json_name = "salCode"];</code>
   * @return The bytes for salCode.
   */
  com.google.protobuf.ByteString
      getSalCodeBytes();

  /**
   * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
   * @return The suburbName.
   */
  java.lang.String getSuburbName();
  /**
   * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
   * @return The bytes for suburbName.
   */
  com.google.protobuf.ByteString
      getSuburbNameBytes();

  /**
   * <code>string state_code = 3 [json_name = "stateCode"];</code>
   * @return The stateCode.
   */
  java.lang.String getStateCode();
  /**
   * <code>string state_code = 3 [json_name = "stateCode"];</code>
   * @return The bytes for stateCode.
   */
  com.google.protobuf.ByteString
      getStateCodeBytes();

  /**
   * <code>int32 declaring_member_count = 4 [json_name = "declaringMemberCount"];</code>
   * @return The declaringMemberCount.
   */
  int getDeclaringMemberCount();

  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  java.util.List<com.shorts.v1alpha1.SuburbPoliticianProperty> 
      getPropertiesList();
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  com.shorts.v1alpha1.SuburbPoliticianProperty getProperties(int index);
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  int getPropertiesCount();
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  java.util.List<? extends com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder> 
      getPropertiesOrBuilderList();
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder getPropertiesOrBuilder(
      int index);

  /**
   * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
   * @return The sourceLicence.
   */
  java.lang.String getSourceLicence();
  /**
   * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
   * @return The bytes for sourceLicence.
   */
  com.google.protobuf.ByteString
      getSourceLicenceBytes();
}
