// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/strategies.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

/**
 * <pre>
 * Response for ListStrategies.
 * </pre>
 *
 * Protobuf type {@code shorts.v1alpha1.ListStrategiesResponse}
 */
@com.google.protobuf.Generated
public final class ListStrategiesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shorts.v1alpha1.ListStrategiesResponse)
    ListStrategiesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListStrategiesResponse");
  }
  // Use ListStrategiesResponse.newBuilder() to construct.
  private ListStrategiesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListStrategiesResponse() {
    strategies_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shorts.v1alpha1.StrategiesProto.internal_static_shorts_v1alpha1_ListStrategiesResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.shorts.v1alpha1.StrategiesProto.internal_static_shorts_v1alpha1_ListStrategiesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shorts.v1alpha1.StrategiesProto.internal_static_shorts_v1alpha1_ListStrategiesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shorts.v1alpha1.ListStrategiesResponse.class, com.shorts.v1alpha1.ListStrategiesResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STRATEGIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.shorts.v1alpha1.Strategy> strategies_;
  /**
   * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
   */
  @java.lang.Override
  public java.util.List<com.shorts.v1alpha1.Strategy> getStrategiesList() {
    return strategies_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.shorts.v1alpha1.StrategyOrBuilder> 
      getStrategiesOrBuilderList() {
    return strategies_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
   */
  @java.lang.Override
  public int getStrategiesCount() {
    return strategies_.size();
  }
  /**
   * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.Strategy getStrategies(int index) {
    return strategies_.get(index);
  }
  /**
   * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.StrategyOrBuilder getStrategiesOrBuilder(
      int index) {
    return strategies_.get(index);
  }

  public static final int REGIME_FIELD_NUMBER = 2;
  private com.shorts.v1alpha1.MarketRegime regime_;
  /**
   * <pre>
   * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
   * </pre>
   *
   * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
   * @return Whether the regime field is set.
   */
  @java.lang.Override
  public boolean hasRegime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
   * </pre>
   *
   * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
   * @return The regime.
   */
  @java.lang.Override
  public com.shorts.v1alpha1.MarketRegime getRegime() {
    return regime_ == null ? com.shorts.v1alpha1.MarketRegime.getDefaultInstance() : regime_;
  }
  /**
   * <pre>
   * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
   * </pre>
   *
   * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.MarketRegimeOrBuilder getRegimeOrBuilder() {
    return regime_ == null ? com.shorts.v1alpha1.MarketRegime.getDefaultInstance() : regime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < strategies_.size(); i++) {
      output.writeMessage(1, strategies_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRegime());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = strategies_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(strategies_.get(i));
          }
          size += 1 * count;
        }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRegime());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shorts.v1alpha1.ListStrategiesResponse)) {
      return super.equals(obj);
    }
    com.shorts.v1alpha1.ListStrategiesResponse other = (com.shorts.v1alpha1.ListStrategiesResponse) obj;

    if (!getStrategiesList()
        .equals(other.getStrategiesList())) return false;
    if (hasRegime() != other.hasRegime()) return false;
    if (hasRegime()) {
      if (!getRegime()
          .equals(other.getRegime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStrategiesCount() > 0) {
      hash = (37 * hash) + STRATEGIES_FIELD_NUMBER;
      hash = (53 * hash) + getStrategiesList().hashCode();
    }
    if (hasRegime()) {
      hash = (37 * hash) + REGIME_FIELD_NUMBER;
      hash = (53 * hash) + getRegime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.shorts.v1alpha1.ListStrategiesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.shorts.v1alpha1.ListStrategiesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.ListStrategiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shorts.v1alpha1.ListStrategiesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for ListStrategies.
   * </pre>
   *
   * Protobuf type {@code shorts.v1alpha1.ListStrategiesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shorts.v1alpha1.ListStrategiesResponse)
      com.shorts.v1alpha1.ListStrategiesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shorts.v1alpha1.StrategiesProto.internal_static_shorts_v1alpha1_ListStrategiesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shorts.v1alpha1.StrategiesProto.internal_static_shorts_v1alpha1_ListStrategiesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shorts.v1alpha1.ListStrategiesResponse.class, com.shorts.v1alpha1.ListStrategiesResponse.Builder.class);
    }

    // Construct using com.shorts.v1alpha1.ListStrategiesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetStrategiesFieldBuilder();
        internalGetRegimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (strategiesBuilder_ == null) {
        strategies_ = java.util.Collections.emptyList();
      } else {
        strategies_ = null;
        strategiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      regime_ = null;
      if (regimeBuilder_ != null) {
        regimeBuilder_.dispose();
        regimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shorts.v1alpha1.StrategiesProto.internal_static_shorts_v1alpha1_ListStrategiesResponse_descriptor;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListStrategiesResponse getDefaultInstanceForType() {
      return com.shorts.v1alpha1.ListStrategiesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListStrategiesResponse build() {
      com.shorts.v1alpha1.ListStrategiesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListStrategiesResponse buildPartial() {
      com.shorts.v1alpha1.ListStrategiesResponse result = new com.shorts.v1alpha1.ListStrategiesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.shorts.v1alpha1.ListStrategiesResponse result) {
      if (strategiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          strategies_ = java.util.Collections.unmodifiableList(strategies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.strategies_ = strategies_;
      } else {
        result.strategies_ = strategiesBuilder_.build();
      }
    }

    private void buildPartial0(com.shorts.v1alpha1.ListStrategiesResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.regime_ = regimeBuilder_ == null
            ? regime_
            : regimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shorts.v1alpha1.ListStrategiesResponse) {
        return mergeFrom((com.shorts.v1alpha1.ListStrategiesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shorts.v1alpha1.ListStrategiesResponse other) {
      if (other == com.shorts.v1alpha1.ListStrategiesResponse.getDefaultInstance()) return this;
      if (strategiesBuilder_ == null) {
        if (!other.strategies_.isEmpty()) {
          if (strategies_.isEmpty()) {
            strategies_ = other.strategies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStrategiesIsMutable();
            strategies_.addAll(other.strategies_);
          }
          onChanged();
        }
      } else {
        if (!other.strategies_.isEmpty()) {
          if (strategiesBuilder_.isEmpty()) {
            strategiesBuilder_.dispose();
            strategiesBuilder_ = null;
            strategies_ = other.strategies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            strategiesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetStrategiesFieldBuilder() : null;
          } else {
            strategiesBuilder_.addAllMessages(other.strategies_);
          }
        }
      }
      if (other.hasRegime()) {
        mergeRegime(other.getRegime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.shorts.v1alpha1.Strategy m =
                  input.readMessage(
                      com.shorts.v1alpha1.Strategy.parser(),
                      extensionRegistry);
              if (strategiesBuilder_ == null) {
                ensureStrategiesIsMutable();
                strategies_.add(m);
              } else {
                strategiesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRegimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.shorts.v1alpha1.Strategy> strategies_ =
      java.util.Collections.emptyList();
    private void ensureStrategiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        strategies_ = new java.util.ArrayList<com.shorts.v1alpha1.Strategy>(strategies_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.Strategy, com.shorts.v1alpha1.Strategy.Builder, com.shorts.v1alpha1.StrategyOrBuilder> strategiesBuilder_;

    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.Strategy> getStrategiesList() {
      if (strategiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(strategies_);
      } else {
        return strategiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public int getStrategiesCount() {
      if (strategiesBuilder_ == null) {
        return strategies_.size();
      } else {
        return strategiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public com.shorts.v1alpha1.Strategy getStrategies(int index) {
      if (strategiesBuilder_ == null) {
        return strategies_.get(index);
      } else {
        return strategiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder setStrategies(
        int index, com.shorts.v1alpha1.Strategy value) {
      if (strategiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStrategiesIsMutable();
        strategies_.set(index, value);
        onChanged();
      } else {
        strategiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder setStrategies(
        int index, com.shorts.v1alpha1.Strategy.Builder builderForValue) {
      if (strategiesBuilder_ == null) {
        ensureStrategiesIsMutable();
        strategies_.set(index, builderForValue.build());
        onChanged();
      } else {
        strategiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder addStrategies(com.shorts.v1alpha1.Strategy value) {
      if (strategiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStrategiesIsMutable();
        strategies_.add(value);
        onChanged();
      } else {
        strategiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder addStrategies(
        int index, com.shorts.v1alpha1.Strategy value) {
      if (strategiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStrategiesIsMutable();
        strategies_.add(index, value);
        onChanged();
      } else {
        strategiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder addStrategies(
        com.shorts.v1alpha1.Strategy.Builder builderForValue) {
      if (strategiesBuilder_ == null) {
        ensureStrategiesIsMutable();
        strategies_.add(builderForValue.build());
        onChanged();
      } else {
        strategiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder addStrategies(
        int index, com.shorts.v1alpha1.Strategy.Builder builderForValue) {
      if (strategiesBuilder_ == null) {
        ensureStrategiesIsMutable();
        strategies_.add(index, builderForValue.build());
        onChanged();
      } else {
        strategiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder addAllStrategies(
        java.lang.Iterable<? extends com.shorts.v1alpha1.Strategy> values) {
      if (strategiesBuilder_ == null) {
        ensureStrategiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strategies_);
        onChanged();
      } else {
        strategiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder clearStrategies() {
      if (strategiesBuilder_ == null) {
        strategies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        strategiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public Builder removeStrategies(int index) {
      if (strategiesBuilder_ == null) {
        ensureStrategiesIsMutable();
        strategies_.remove(index);
        onChanged();
      } else {
        strategiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public com.shorts.v1alpha1.Strategy.Builder getStrategiesBuilder(
        int index) {
      return internalGetStrategiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public com.shorts.v1alpha1.StrategyOrBuilder getStrategiesOrBuilder(
        int index) {
      if (strategiesBuilder_ == null) {
        return strategies_.get(index);  } else {
        return strategiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public java.util.List<? extends com.shorts.v1alpha1.StrategyOrBuilder> 
         getStrategiesOrBuilderList() {
      if (strategiesBuilder_ != null) {
        return strategiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(strategies_);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public com.shorts.v1alpha1.Strategy.Builder addStrategiesBuilder() {
      return internalGetStrategiesFieldBuilder().addBuilder(
          com.shorts.v1alpha1.Strategy.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public com.shorts.v1alpha1.Strategy.Builder addStrategiesBuilder(
        int index) {
      return internalGetStrategiesFieldBuilder().addBuilder(
          index, com.shorts.v1alpha1.Strategy.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.Strategy strategies = 1 [json_name = "strategies"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.Strategy.Builder> 
         getStrategiesBuilderList() {
      return internalGetStrategiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.Strategy, com.shorts.v1alpha1.Strategy.Builder, com.shorts.v1alpha1.StrategyOrBuilder> 
        internalGetStrategiesFieldBuilder() {
      if (strategiesBuilder_ == null) {
        strategiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.shorts.v1alpha1.Strategy, com.shorts.v1alpha1.Strategy.Builder, com.shorts.v1alpha1.StrategyOrBuilder>(
                strategies_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        strategies_ = null;
      }
      return strategiesBuilder_;
    }

    private com.shorts.v1alpha1.MarketRegime regime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.shorts.v1alpha1.MarketRegime, com.shorts.v1alpha1.MarketRegime.Builder, com.shorts.v1alpha1.MarketRegimeOrBuilder> regimeBuilder_;
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     * @return Whether the regime field is set.
     */
    public boolean hasRegime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     * @return The regime.
     */
    public com.shorts.v1alpha1.MarketRegime getRegime() {
      if (regimeBuilder_ == null) {
        return regime_ == null ? com.shorts.v1alpha1.MarketRegime.getDefaultInstance() : regime_;
      } else {
        return regimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    public Builder setRegime(com.shorts.v1alpha1.MarketRegime value) {
      if (regimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        regime_ = value;
      } else {
        regimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    public Builder setRegime(
        com.shorts.v1alpha1.MarketRegime.Builder builderForValue) {
      if (regimeBuilder_ == null) {
        regime_ = builderForValue.build();
      } else {
        regimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    public Builder mergeRegime(com.shorts.v1alpha1.MarketRegime value) {
      if (regimeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          regime_ != null &&
          regime_ != com.shorts.v1alpha1.MarketRegime.getDefaultInstance()) {
          getRegimeBuilder().mergeFrom(value);
        } else {
          regime_ = value;
        }
      } else {
        regimeBuilder_.mergeFrom(value);
      }
      if (regime_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    public Builder clearRegime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      regime_ = null;
      if (regimeBuilder_ != null) {
        regimeBuilder_.dispose();
        regimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    public com.shorts.v1alpha1.MarketRegime.Builder getRegimeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRegimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    public com.shorts.v1alpha1.MarketRegimeOrBuilder getRegimeOrBuilder() {
      if (regimeBuilder_ != null) {
        return regimeBuilder_.getMessageOrBuilder();
      } else {
        return regime_ == null ?
            com.shorts.v1alpha1.MarketRegime.getDefaultInstance() : regime_;
      }
    }
    /**
     * <pre>
     * Verdict is strategy-neutral here; GetStrategyPicks phrases it per strategy.
     * </pre>
     *
     * <code>.shorts.v1alpha1.MarketRegime regime = 2 [json_name = "regime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.shorts.v1alpha1.MarketRegime, com.shorts.v1alpha1.MarketRegime.Builder, com.shorts.v1alpha1.MarketRegimeOrBuilder> 
        internalGetRegimeFieldBuilder() {
      if (regimeBuilder_ == null) {
        regimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.shorts.v1alpha1.MarketRegime, com.shorts.v1alpha1.MarketRegime.Builder, com.shorts.v1alpha1.MarketRegimeOrBuilder>(
                getRegime(),
                getParentForChildren(),
                isClean());
        regime_ = null;
      }
      return regimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:shorts.v1alpha1.ListStrategiesResponse)
  }

  // @@protoc_insertion_point(class_scope:shorts.v1alpha1.ListStrategiesResponse)
  private static final com.shorts.v1alpha1.ListStrategiesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shorts.v1alpha1.ListStrategiesResponse();
  }

  public static com.shorts.v1alpha1.ListStrategiesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListStrategiesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListStrategiesResponse>() {
    @java.lang.Override
    public ListStrategiesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListStrategiesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListStrategiesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shorts.v1alpha1.ListStrategiesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

