// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/politicians.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

/**
 * Protobuf type {@code shorts.v1alpha1.ListSuburbPoliticiansResponse}
 */
@com.google.protobuf.Generated
public final class ListSuburbPoliticiansResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shorts.v1alpha1.ListSuburbPoliticiansResponse)
    ListSuburbPoliticiansResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListSuburbPoliticiansResponse");
  }
  // Use ListSuburbPoliticiansResponse.newBuilder() to construct.
  private ListSuburbPoliticiansResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListSuburbPoliticiansResponse() {
    salCode_ = "";
    suburbName_ = "";
    stateCode_ = "";
    properties_ = java.util.Collections.emptyList();
    sourceLicence_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_ListSuburbPoliticiansResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_ListSuburbPoliticiansResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_ListSuburbPoliticiansResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shorts.v1alpha1.ListSuburbPoliticiansResponse.class, com.shorts.v1alpha1.ListSuburbPoliticiansResponse.Builder.class);
  }

  public static final int SAL_CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object salCode_ = "";
  /**
   * <code>string sal_code = 1 [json_name = "salCode"];</code>
   * @return The salCode.
   */
  @java.lang.Override
  public java.lang.String getSalCode() {
    java.lang.Object ref = salCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      salCode_ = s;
      return s;
    }
  }
  /**
   * <code>string sal_code = 1 [json_name = "salCode"];</code>
   * @return The bytes for salCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSalCodeBytes() {
    java.lang.Object ref = salCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      salCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBURB_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object suburbName_ = "";
  /**
   * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
   * @return The suburbName.
   */
  @java.lang.Override
  public java.lang.String getSuburbName() {
    java.lang.Object ref = suburbName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      suburbName_ = s;
      return s;
    }
  }
  /**
   * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
   * @return The bytes for suburbName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSuburbNameBytes() {
    java.lang.Object ref = suburbName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      suburbName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_CODE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stateCode_ = "";
  /**
   * <code>string state_code = 3 [json_name = "stateCode"];</code>
   * @return The stateCode.
   */
  @java.lang.Override
  public java.lang.String getStateCode() {
    java.lang.Object ref = stateCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stateCode_ = s;
      return s;
    }
  }
  /**
   * <code>string state_code = 3 [json_name = "stateCode"];</code>
   * @return The bytes for stateCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateCodeBytes() {
    java.lang.Object ref = stateCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stateCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DECLARING_MEMBER_COUNT_FIELD_NUMBER = 4;
  private int declaringMemberCount_ = 0;
  /**
   * <code>int32 declaring_member_count = 4 [json_name = "declaringMemberCount"];</code>
   * @return The declaringMemberCount.
   */
  @java.lang.Override
  public int getDeclaringMemberCount() {
    return declaringMemberCount_;
  }

  public static final int PROPERTIES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.shorts.v1alpha1.SuburbPoliticianProperty> properties_;
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  @java.lang.Override
  public java.util.List<com.shorts.v1alpha1.SuburbPoliticianProperty> getPropertiesList() {
    return properties_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder> 
      getPropertiesOrBuilderList() {
    return properties_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  @java.lang.Override
  public int getPropertiesCount() {
    return properties_.size();
  }
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.SuburbPoliticianProperty getProperties(int index) {
    return properties_.get(index);
  }
  /**
   * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder getPropertiesOrBuilder(
      int index) {
    return properties_.get(index);
  }

  public static final int SOURCE_LICENCE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceLicence_ = "";
  /**
   * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
   * @return The sourceLicence.
   */
  @java.lang.Override
  public java.lang.String getSourceLicence() {
    java.lang.Object ref = sourceLicence_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceLicence_ = s;
      return s;
    }
  }
  /**
   * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
   * @return The bytes for sourceLicence.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceLicenceBytes() {
    java.lang.Object ref = sourceLicence_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceLicence_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(salCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, salCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(suburbName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, suburbName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, stateCode_);
    }
    if (declaringMemberCount_ != 0) {
      output.writeInt32(4, declaringMemberCount_);
    }
    for (int i = 0; i < properties_.size(); i++) {
      output.writeMessage(5, properties_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceLicence_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, sourceLicence_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(salCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, salCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(suburbName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, suburbName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, stateCode_);
    }
    if (declaringMemberCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, declaringMemberCount_);
    }

        {
          final int count = properties_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(properties_.get(i));
          }
          size += 1 * count;
        }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceLicence_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, sourceLicence_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shorts.v1alpha1.ListSuburbPoliticiansResponse)) {
      return super.equals(obj);
    }
    com.shorts.v1alpha1.ListSuburbPoliticiansResponse other = (com.shorts.v1alpha1.ListSuburbPoliticiansResponse) obj;

    if (!getSalCode()
        .equals(other.getSalCode())) return false;
    if (!getSuburbName()
        .equals(other.getSuburbName())) return false;
    if (!getStateCode()
        .equals(other.getStateCode())) return false;
    if (getDeclaringMemberCount()
        != other.getDeclaringMemberCount()) return false;
    if (!getPropertiesList()
        .equals(other.getPropertiesList())) return false;
    if (!getSourceLicence()
        .equals(other.getSourceLicence())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SAL_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getSalCode().hashCode();
    hash = (37 * hash) + SUBURB_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSuburbName().hashCode();
    hash = (37 * hash) + STATE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getStateCode().hashCode();
    hash = (37 * hash) + DECLARING_MEMBER_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getDeclaringMemberCount();
    if (getPropertiesCount() > 0) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + getPropertiesList().hashCode();
    }
    hash = (37 * hash) + SOURCE_LICENCE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceLicence().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shorts.v1alpha1.ListSuburbPoliticiansResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code shorts.v1alpha1.ListSuburbPoliticiansResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shorts.v1alpha1.ListSuburbPoliticiansResponse)
      com.shorts.v1alpha1.ListSuburbPoliticiansResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_ListSuburbPoliticiansResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_ListSuburbPoliticiansResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shorts.v1alpha1.ListSuburbPoliticiansResponse.class, com.shorts.v1alpha1.ListSuburbPoliticiansResponse.Builder.class);
    }

    // Construct using com.shorts.v1alpha1.ListSuburbPoliticiansResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      salCode_ = "";
      suburbName_ = "";
      stateCode_ = "";
      declaringMemberCount_ = 0;
      if (propertiesBuilder_ == null) {
        properties_ = java.util.Collections.emptyList();
      } else {
        properties_ = null;
        propertiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      sourceLicence_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_ListSuburbPoliticiansResponse_descriptor;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListSuburbPoliticiansResponse getDefaultInstanceForType() {
      return com.shorts.v1alpha1.ListSuburbPoliticiansResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListSuburbPoliticiansResponse build() {
      com.shorts.v1alpha1.ListSuburbPoliticiansResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListSuburbPoliticiansResponse buildPartial() {
      com.shorts.v1alpha1.ListSuburbPoliticiansResponse result = new com.shorts.v1alpha1.ListSuburbPoliticiansResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.shorts.v1alpha1.ListSuburbPoliticiansResponse result) {
      if (propertiesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.properties_ = properties_;
      } else {
        result.properties_ = propertiesBuilder_.build();
      }
    }

    private void buildPartial0(com.shorts.v1alpha1.ListSuburbPoliticiansResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.salCode_ = salCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.suburbName_ = suburbName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stateCode_ = stateCode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.declaringMemberCount_ = declaringMemberCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.sourceLicence_ = sourceLicence_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shorts.v1alpha1.ListSuburbPoliticiansResponse) {
        return mergeFrom((com.shorts.v1alpha1.ListSuburbPoliticiansResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shorts.v1alpha1.ListSuburbPoliticiansResponse other) {
      if (other == com.shorts.v1alpha1.ListSuburbPoliticiansResponse.getDefaultInstance()) return this;
      if (!other.getSalCode().isEmpty()) {
        salCode_ = other.salCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSuburbName().isEmpty()) {
        suburbName_ = other.suburbName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getStateCode().isEmpty()) {
        stateCode_ = other.stateCode_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getDeclaringMemberCount() != 0) {
        setDeclaringMemberCount(other.getDeclaringMemberCount());
      }
      if (propertiesBuilder_ == null) {
        if (!other.properties_.isEmpty()) {
          if (properties_.isEmpty()) {
            properties_ = other.properties_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePropertiesIsMutable();
            properties_.addAll(other.properties_);
          }
          onChanged();
        }
      } else {
        if (!other.properties_.isEmpty()) {
          if (propertiesBuilder_.isEmpty()) {
            propertiesBuilder_.dispose();
            propertiesBuilder_ = null;
            properties_ = other.properties_;
            bitField0_ = (bitField0_ & ~0x00000010);
            propertiesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPropertiesFieldBuilder() : null;
          } else {
            propertiesBuilder_.addAllMessages(other.properties_);
          }
        }
      }
      if (!other.getSourceLicence().isEmpty()) {
        sourceLicence_ = other.sourceLicence_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              salCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              suburbName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              stateCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              declaringMemberCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.shorts.v1alpha1.SuburbPoliticianProperty m =
                  input.readMessage(
                      com.shorts.v1alpha1.SuburbPoliticianProperty.parser(),
                      extensionRegistry);
              if (propertiesBuilder_ == null) {
                ensurePropertiesIsMutable();
                properties_.add(m);
              } else {
                propertiesBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              sourceLicence_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object salCode_ = "";
    /**
     * <code>string sal_code = 1 [json_name = "salCode"];</code>
     * @return The salCode.
     */
    public java.lang.String getSalCode() {
      java.lang.Object ref = salCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sal_code = 1 [json_name = "salCode"];</code>
     * @return The bytes for salCode.
     */
    public com.google.protobuf.ByteString
        getSalCodeBytes() {
      java.lang.Object ref = salCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sal_code = 1 [json_name = "salCode"];</code>
     * @param value The salCode to set.
     * @return This builder for chaining.
     */
    public Builder setSalCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      salCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sal_code = 1 [json_name = "salCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSalCode() {
      salCode_ = getDefaultInstance().getSalCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sal_code = 1 [json_name = "salCode"];</code>
     * @param value The bytes for salCode to set.
     * @return This builder for chaining.
     */
    public Builder setSalCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      salCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object suburbName_ = "";
    /**
     * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
     * @return The suburbName.
     */
    public java.lang.String getSuburbName() {
      java.lang.Object ref = suburbName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        suburbName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
     * @return The bytes for suburbName.
     */
    public com.google.protobuf.ByteString
        getSuburbNameBytes() {
      java.lang.Object ref = suburbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        suburbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
     * @param value The suburbName to set.
     * @return This builder for chaining.
     */
    public Builder setSuburbName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      suburbName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSuburbName() {
      suburbName_ = getDefaultInstance().getSuburbName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string suburb_name = 2 [json_name = "suburbName"];</code>
     * @param value The bytes for suburbName to set.
     * @return This builder for chaining.
     */
    public Builder setSuburbNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      suburbName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object stateCode_ = "";
    /**
     * <code>string state_code = 3 [json_name = "stateCode"];</code>
     * @return The stateCode.
     */
    public java.lang.String getStateCode() {
      java.lang.Object ref = stateCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stateCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state_code = 3 [json_name = "stateCode"];</code>
     * @return The bytes for stateCode.
     */
    public com.google.protobuf.ByteString
        getStateCodeBytes() {
      java.lang.Object ref = stateCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state_code = 3 [json_name = "stateCode"];</code>
     * @param value The stateCode to set.
     * @return This builder for chaining.
     */
    public Builder setStateCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stateCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string state_code = 3 [json_name = "stateCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStateCode() {
      stateCode_ = getDefaultInstance().getStateCode();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string state_code = 3 [json_name = "stateCode"];</code>
     * @param value The bytes for stateCode to set.
     * @return This builder for chaining.
     */
    public Builder setStateCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stateCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int declaringMemberCount_ ;
    /**
     * <code>int32 declaring_member_count = 4 [json_name = "declaringMemberCount"];</code>
     * @return The declaringMemberCount.
     */
    @java.lang.Override
    public int getDeclaringMemberCount() {
      return declaringMemberCount_;
    }
    /**
     * <code>int32 declaring_member_count = 4 [json_name = "declaringMemberCount"];</code>
     * @param value The declaringMemberCount to set.
     * @return This builder for chaining.
     */
    public Builder setDeclaringMemberCount(int value) {

      declaringMemberCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 declaring_member_count = 4 [json_name = "declaringMemberCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeclaringMemberCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      declaringMemberCount_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.shorts.v1alpha1.SuburbPoliticianProperty> properties_ =
      java.util.Collections.emptyList();
    private void ensurePropertiesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        properties_ = new java.util.ArrayList<com.shorts.v1alpha1.SuburbPoliticianProperty>(properties_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.SuburbPoliticianProperty, com.shorts.v1alpha1.SuburbPoliticianProperty.Builder, com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder> propertiesBuilder_;

    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.SuburbPoliticianProperty> getPropertiesList() {
      if (propertiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(properties_);
      } else {
        return propertiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public int getPropertiesCount() {
      if (propertiesBuilder_ == null) {
        return properties_.size();
      } else {
        return propertiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public com.shorts.v1alpha1.SuburbPoliticianProperty getProperties(int index) {
      if (propertiesBuilder_ == null) {
        return properties_.get(index);
      } else {
        return propertiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder setProperties(
        int index, com.shorts.v1alpha1.SuburbPoliticianProperty value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertiesIsMutable();
        properties_.set(index, value);
        onChanged();
      } else {
        propertiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder setProperties(
        int index, com.shorts.v1alpha1.SuburbPoliticianProperty.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.set(index, builderForValue.build());
        onChanged();
      } else {
        propertiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder addProperties(com.shorts.v1alpha1.SuburbPoliticianProperty value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertiesIsMutable();
        properties_.add(value);
        onChanged();
      } else {
        propertiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder addProperties(
        int index, com.shorts.v1alpha1.SuburbPoliticianProperty value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertiesIsMutable();
        properties_.add(index, value);
        onChanged();
      } else {
        propertiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder addProperties(
        com.shorts.v1alpha1.SuburbPoliticianProperty.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.add(builderForValue.build());
        onChanged();
      } else {
        propertiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder addProperties(
        int index, com.shorts.v1alpha1.SuburbPoliticianProperty.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.add(index, builderForValue.build());
        onChanged();
      } else {
        propertiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder addAllProperties(
        java.lang.Iterable<? extends com.shorts.v1alpha1.SuburbPoliticianProperty> values) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, properties_);
        onChanged();
      } else {
        propertiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder clearProperties() {
      if (propertiesBuilder_ == null) {
        properties_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        propertiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public Builder removeProperties(int index) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.remove(index);
        onChanged();
      } else {
        propertiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public com.shorts.v1alpha1.SuburbPoliticianProperty.Builder getPropertiesBuilder(
        int index) {
      return internalGetPropertiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      if (propertiesBuilder_ == null) {
        return properties_.get(index);  } else {
        return propertiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public java.util.List<? extends com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder> 
         getPropertiesOrBuilderList() {
      if (propertiesBuilder_ != null) {
        return propertiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(properties_);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public com.shorts.v1alpha1.SuburbPoliticianProperty.Builder addPropertiesBuilder() {
      return internalGetPropertiesFieldBuilder().addBuilder(
          com.shorts.v1alpha1.SuburbPoliticianProperty.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public com.shorts.v1alpha1.SuburbPoliticianProperty.Builder addPropertiesBuilder(
        int index) {
      return internalGetPropertiesFieldBuilder().addBuilder(
          index, com.shorts.v1alpha1.SuburbPoliticianProperty.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.SuburbPoliticianProperty properties = 5 [json_name = "properties"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.SuburbPoliticianProperty.Builder> 
         getPropertiesBuilderList() {
      return internalGetPropertiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.SuburbPoliticianProperty, com.shorts.v1alpha1.SuburbPoliticianProperty.Builder, com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder> 
        internalGetPropertiesFieldBuilder() {
      if (propertiesBuilder_ == null) {
        propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.shorts.v1alpha1.SuburbPoliticianProperty, com.shorts.v1alpha1.SuburbPoliticianProperty.Builder, com.shorts.v1alpha1.SuburbPoliticianPropertyOrBuilder>(
                properties_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        properties_ = null;
      }
      return propertiesBuilder_;
    }

    private java.lang.Object sourceLicence_ = "";
    /**
     * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
     * @return The sourceLicence.
     */
    public java.lang.String getSourceLicence() {
      java.lang.Object ref = sourceLicence_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceLicence_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
     * @return The bytes for sourceLicence.
     */
    public com.google.protobuf.ByteString
        getSourceLicenceBytes() {
      java.lang.Object ref = sourceLicence_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceLicence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
     * @param value The sourceLicence to set.
     * @return This builder for chaining.
     */
    public Builder setSourceLicence(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceLicence_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceLicence() {
      sourceLicence_ = getDefaultInstance().getSourceLicence();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string source_licence = 6 [json_name = "sourceLicence"];</code>
     * @param value The bytes for sourceLicence to set.
     * @return This builder for chaining.
     */
    public Builder setSourceLicenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceLicence_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:shorts.v1alpha1.ListSuburbPoliticiansResponse)
  }

  // @@protoc_insertion_point(class_scope:shorts.v1alpha1.ListSuburbPoliticiansResponse)
  private static final com.shorts.v1alpha1.ListSuburbPoliticiansResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shorts.v1alpha1.ListSuburbPoliticiansResponse();
  }

  public static com.shorts.v1alpha1.ListSuburbPoliticiansResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListSuburbPoliticiansResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListSuburbPoliticiansResponse>() {
    @java.lang.Override
    public ListSuburbPoliticiansResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListSuburbPoliticiansResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListSuburbPoliticiansResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shorts.v1alpha1.ListSuburbPoliticiansResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

