// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/shorts.proto
// Protobuf Java Version: 4.34.0

package com.shorts.v1alpha1;

/**
 * <pre>
 * List enrichment jobs response
 * </pre>
 *
 * Protobuf type {@code shorts.v1alpha1.ListEnrichmentJobsResponse}
 */
@com.google.protobuf.Generated
public final class ListEnrichmentJobsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shorts.v1alpha1.ListEnrichmentJobsResponse)
    ListEnrichmentJobsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "ListEnrichmentJobsResponse");
  }
  // Use ListEnrichmentJobsResponse.newBuilder() to construct.
  private ListEnrichmentJobsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListEnrichmentJobsResponse() {
    jobs_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shorts.v1alpha1.ShortsProto.internal_static_shorts_v1alpha1_ListEnrichmentJobsResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.shorts.v1alpha1.ShortsProto.internal_static_shorts_v1alpha1_ListEnrichmentJobsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shorts.v1alpha1.ShortsProto.internal_static_shorts_v1alpha1_ListEnrichmentJobsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shorts.v1alpha1.ListEnrichmentJobsResponse.class, com.shorts.v1alpha1.ListEnrichmentJobsResponse.Builder.class);
  }

  public static final int JOBS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.shorts.v1alpha1.EnrichmentJob> jobs_;
  /**
   * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.shorts.v1alpha1.EnrichmentJob> getJobsList() {
    return jobs_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.shorts.v1alpha1.EnrichmentJobOrBuilder> 
      getJobsOrBuilderList() {
    return jobs_;
  }
  /**
   * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public int getJobsCount() {
    return jobs_.size();
  }
  /**
   * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.EnrichmentJob getJobs(int index) {
    return jobs_.get(index);
  }
  /**
   * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public com.shorts.v1alpha1.EnrichmentJobOrBuilder getJobsOrBuilder(
      int index) {
    return jobs_.get(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 2;
  private int totalCount_ = 0;
  /**
   * <code>int32 total_count = 2 [json_name = "totalCount"];</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobs_.size(); i++) {
      output.writeMessage(1, jobs_.get(i));
    }
    if (totalCount_ != 0) {
      output.writeInt32(2, totalCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = jobs_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(jobs_.get(i));
          }
          size += 1 * count;
        }
    if (totalCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shorts.v1alpha1.ListEnrichmentJobsResponse)) {
      return super.equals(obj);
    }
    com.shorts.v1alpha1.ListEnrichmentJobsResponse other = (com.shorts.v1alpha1.ListEnrichmentJobsResponse) obj;

    if (!getJobsList()
        .equals(other.getJobsList())) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobsCount() > 0) {
      hash = (37 * hash) + JOBS_FIELD_NUMBER;
      hash = (53 * hash) + getJobsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shorts.v1alpha1.ListEnrichmentJobsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * List enrichment jobs response
   * </pre>
   *
   * Protobuf type {@code shorts.v1alpha1.ListEnrichmentJobsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shorts.v1alpha1.ListEnrichmentJobsResponse)
      com.shorts.v1alpha1.ListEnrichmentJobsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shorts.v1alpha1.ShortsProto.internal_static_shorts_v1alpha1_ListEnrichmentJobsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shorts.v1alpha1.ShortsProto.internal_static_shorts_v1alpha1_ListEnrichmentJobsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shorts.v1alpha1.ListEnrichmentJobsResponse.class, com.shorts.v1alpha1.ListEnrichmentJobsResponse.Builder.class);
    }

    // Construct using com.shorts.v1alpha1.ListEnrichmentJobsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
      } else {
        jobs_ = null;
        jobsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shorts.v1alpha1.ShortsProto.internal_static_shorts_v1alpha1_ListEnrichmentJobsResponse_descriptor;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListEnrichmentJobsResponse getDefaultInstanceForType() {
      return com.shorts.v1alpha1.ListEnrichmentJobsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListEnrichmentJobsResponse build() {
      com.shorts.v1alpha1.ListEnrichmentJobsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.ListEnrichmentJobsResponse buildPartial() {
      com.shorts.v1alpha1.ListEnrichmentJobsResponse result = new com.shorts.v1alpha1.ListEnrichmentJobsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.shorts.v1alpha1.ListEnrichmentJobsResponse result) {
      if (jobsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobs_ = jobs_;
      } else {
        result.jobs_ = jobsBuilder_.build();
      }
    }

    private void buildPartial0(com.shorts.v1alpha1.ListEnrichmentJobsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalCount_ = totalCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shorts.v1alpha1.ListEnrichmentJobsResponse) {
        return mergeFrom((com.shorts.v1alpha1.ListEnrichmentJobsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shorts.v1alpha1.ListEnrichmentJobsResponse other) {
      if (other == com.shorts.v1alpha1.ListEnrichmentJobsResponse.getDefaultInstance()) return this;
      if (jobsBuilder_ == null) {
        if (!other.jobs_.isEmpty()) {
          if (jobs_.isEmpty()) {
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobsIsMutable();
            jobs_.addAll(other.jobs_);
          }
          onChanged();
        }
      } else {
        if (!other.jobs_.isEmpty()) {
          if (jobsBuilder_.isEmpty()) {
            jobsBuilder_.dispose();
            jobsBuilder_ = null;
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetJobsFieldBuilder() : null;
          } else {
            jobsBuilder_.addAllMessages(other.jobs_);
          }
        }
      }
      if (other.getTotalCount() != 0) {
        setTotalCount(other.getTotalCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.shorts.v1alpha1.EnrichmentJob m =
                  input.readMessage(
                      com.shorts.v1alpha1.EnrichmentJob.parser(),
                      extensionRegistry);
              if (jobsBuilder_ == null) {
                ensureJobsIsMutable();
                jobs_.add(m);
              } else {
                jobsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              totalCount_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.shorts.v1alpha1.EnrichmentJob> jobs_ =
      java.util.Collections.emptyList();
    private void ensureJobsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobs_ = new java.util.ArrayList<com.shorts.v1alpha1.EnrichmentJob>(jobs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.EnrichmentJob, com.shorts.v1alpha1.EnrichmentJob.Builder, com.shorts.v1alpha1.EnrichmentJobOrBuilder> jobsBuilder_;

    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.EnrichmentJob> getJobsList() {
      if (jobsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobs_);
      } else {
        return jobsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public int getJobsCount() {
      if (jobsBuilder_ == null) {
        return jobs_.size();
      } else {
        return jobsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public com.shorts.v1alpha1.EnrichmentJob getJobs(int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);
      } else {
        return jobsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder setJobs(
        int index, com.shorts.v1alpha1.EnrichmentJob value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.set(index, value);
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder setJobs(
        int index, com.shorts.v1alpha1.EnrichmentJob.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder addJobs(com.shorts.v1alpha1.EnrichmentJob value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder addJobs(
        int index, com.shorts.v1alpha1.EnrichmentJob value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(index, value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder addJobs(
        com.shorts.v1alpha1.EnrichmentJob.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder addJobs(
        int index, com.shorts.v1alpha1.EnrichmentJob.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder addAllJobs(
        java.lang.Iterable<? extends com.shorts.v1alpha1.EnrichmentJob> values) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobs_);
        onChanged();
      } else {
        jobsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder clearJobs() {
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public Builder removeJobs(int index) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.remove(index);
        onChanged();
      } else {
        jobsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public com.shorts.v1alpha1.EnrichmentJob.Builder getJobsBuilder(
        int index) {
      return internalGetJobsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public com.shorts.v1alpha1.EnrichmentJobOrBuilder getJobsOrBuilder(
        int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);  } else {
        return jobsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public java.util.List<? extends com.shorts.v1alpha1.EnrichmentJobOrBuilder> 
         getJobsOrBuilderList() {
      if (jobsBuilder_ != null) {
        return jobsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobs_);
      }
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public com.shorts.v1alpha1.EnrichmentJob.Builder addJobsBuilder() {
      return internalGetJobsFieldBuilder().addBuilder(
          com.shorts.v1alpha1.EnrichmentJob.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public com.shorts.v1alpha1.EnrichmentJob.Builder addJobsBuilder(
        int index) {
      return internalGetJobsFieldBuilder().addBuilder(
          index, com.shorts.v1alpha1.EnrichmentJob.getDefaultInstance());
    }
    /**
     * <code>repeated .shorts.v1alpha1.EnrichmentJob jobs = 1 [json_name = "jobs"];</code>
     */
    public java.util.List<com.shorts.v1alpha1.EnrichmentJob.Builder> 
         getJobsBuilderList() {
      return internalGetJobsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.shorts.v1alpha1.EnrichmentJob, com.shorts.v1alpha1.EnrichmentJob.Builder, com.shorts.v1alpha1.EnrichmentJobOrBuilder> 
        internalGetJobsFieldBuilder() {
      if (jobsBuilder_ == null) {
        jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.shorts.v1alpha1.EnrichmentJob, com.shorts.v1alpha1.EnrichmentJob.Builder, com.shorts.v1alpha1.EnrichmentJobOrBuilder>(
                jobs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobs_ = null;
      }
      return jobsBuilder_;
    }

    private int totalCount_ ;
    /**
     * <code>int32 total_count = 2 [json_name = "totalCount"];</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int32 total_count = 2 [json_name = "totalCount"];</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {

      totalCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_count = 2 [json_name = "totalCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:shorts.v1alpha1.ListEnrichmentJobsResponse)
  }

  // @@protoc_insertion_point(class_scope:shorts.v1alpha1.ListEnrichmentJobsResponse)
  private static final com.shorts.v1alpha1.ListEnrichmentJobsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shorts.v1alpha1.ListEnrichmentJobsResponse();
  }

  public static com.shorts.v1alpha1.ListEnrichmentJobsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListEnrichmentJobsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListEnrichmentJobsResponse>() {
    @java.lang.Override
    public ListEnrichmentJobsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListEnrichmentJobsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListEnrichmentJobsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shorts.v1alpha1.ListEnrichmentJobsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

