// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/search.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public final class SearchProto extends com.google.protobuf.GeneratedFile {
  private SearchProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "SearchProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_SearchStocksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_SearchStocksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_SearchStocksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_SearchStocksResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034shorts/v1alpha1/search.proto\022\017shorts.v" +
      "1alpha1\032\034stocks/v1alpha1/stocks.proto\032\030o" +
      "ptions/v1/options.proto\"j\n\023SearchStocksR" +
      "equest\022\024\n\005query\030\001 \001(\tR\005query\022\024\n\005limit\030\002 " +
      "\001(\005R\005limit\022\'\n\017include_details\030\003 \001(\010R\016inc" +
      "ludeDetails\"r\n\024SearchStocksResponse\022\024\n\005q" +
      "uery\030\001 \001(\tR\005query\022.\n\006stocks\030\002 \003(\0132\026.stoc" +
      "ks.v1alpha1.StockR\006stocks\022\024\n\005count\030\003 \001(\005" +
      "R\005count2r\n\rSearchService\022a\n\014SearchStocks" +
      "\022$.shorts.v1alpha1.SearchStocksRequest\032%" +
      ".shorts.v1alpha1.SearchStocksResponse\"\004\200" +
      "\265\030\001B\332\001\n\023com.shorts.v1alpha1B\013SearchProto" +
      "P\001ZYgithub.com/castlemilk/shorted.com.au" +
      "/services/gen/proto/go/shorts/v1alpha1;s" +
      "hortsv1alpha1\242\002\003SXX\252\002\017Shorts.V1alpha1\312\002\017" +
      "Shorts\\V1alpha1\342\002\033Shorts\\V1alpha1\\GPBMet" +
      "adata\352\002\020Shorts::V1alpha1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stocks.v1alpha1.StocksProto.getDescriptor(),
          com.shortedapi.options.v1.OptionsProto.getDescriptor(),
        });
    internal_static_shorts_v1alpha1_SearchStocksRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_shorts_v1alpha1_SearchStocksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_SearchStocksRequest_descriptor,
        new java.lang.String[] { "Query", "Limit", "IncludeDetails", });
    internal_static_shorts_v1alpha1_SearchStocksResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_shorts_v1alpha1_SearchStocksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_SearchStocksResponse_descriptor,
        new java.lang.String[] { "Query", "Stocks", "Count", });
    descriptor.resolveAllFeaturesImmutable();
    com.stocks.v1alpha1.StocksProto.getDescriptor();
    com.shortedapi.options.v1.OptionsProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.shortedapi.options.v1.OptionsProto.visibility);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
