// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/politicians.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

/**
 * Protobuf type {@code shorts.v1alpha1.StateTotal}
 */
@com.google.protobuf.Generated
public final class StateTotal extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:shorts.v1alpha1.StateTotal)
    StateTotalOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StateTotal");
  }
  // Use StateTotal.newBuilder() to construct.
  private StateTotal(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StateTotal() {
    stateCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_StateTotal_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_StateTotal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_StateTotal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.shorts.v1alpha1.StateTotal.class, com.shorts.v1alpha1.StateTotal.Builder.class);
  }

  public static final int STATE_CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stateCode_ = "";
  /**
   * <code>string state_code = 1 [json_name = "stateCode"];</code>
   * @return The stateCode.
   */
  @java.lang.Override
  public java.lang.String getStateCode() {
    java.lang.Object ref = stateCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stateCode_ = s;
      return s;
    }
  }
  /**
   * <code>string state_code = 1 [json_name = "stateCode"];</code>
   * @return The bytes for stateCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateCodeBytes() {
    java.lang.Object ref = stateCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stateCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEOPLE_FIELD_NUMBER = 2;
  private int people_ = 0;
  /**
   * <code>int32 people = 2 [json_name = "people"];</code>
   * @return The people.
   */
  @java.lang.Override
  public int getPeople() {
    return people_;
  }

  public static final int COMPANIES_FIELD_NUMBER = 3;
  private int companies_ = 0;
  /**
   * <code>int32 companies = 3 [json_name = "companies"];</code>
   * @return The companies.
   */
  @java.lang.Override
  public int getCompanies() {
    return companies_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, stateCode_);
    }
    if (people_ != 0) {
      output.writeInt32(2, people_);
    }
    if (companies_ != 0) {
      output.writeInt32(3, companies_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, stateCode_);
    }
    if (people_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, people_);
    }
    if (companies_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, companies_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.shorts.v1alpha1.StateTotal)) {
      return super.equals(obj);
    }
    com.shorts.v1alpha1.StateTotal other = (com.shorts.v1alpha1.StateTotal) obj;

    if (!getStateCode()
        .equals(other.getStateCode())) return false;
    if (getPeople()
        != other.getPeople()) return false;
    if (getCompanies()
        != other.getCompanies()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getStateCode().hashCode();
    hash = (37 * hash) + PEOPLE_FIELD_NUMBER;
    hash = (53 * hash) + getPeople();
    hash = (37 * hash) + COMPANIES_FIELD_NUMBER;
    hash = (53 * hash) + getCompanies();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.shorts.v1alpha1.StateTotal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.shorts.v1alpha1.StateTotal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.shorts.v1alpha1.StateTotal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.shorts.v1alpha1.StateTotal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.shorts.v1alpha1.StateTotal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code shorts.v1alpha1.StateTotal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shorts.v1alpha1.StateTotal)
      com.shorts.v1alpha1.StateTotalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_StateTotal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_StateTotal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shorts.v1alpha1.StateTotal.class, com.shorts.v1alpha1.StateTotal.Builder.class);
    }

    // Construct using com.shorts.v1alpha1.StateTotal.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      stateCode_ = "";
      people_ = 0;
      companies_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.shorts.v1alpha1.PoliticiansProto.internal_static_shorts_v1alpha1_StateTotal_descriptor;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.StateTotal getDefaultInstanceForType() {
      return com.shorts.v1alpha1.StateTotal.getDefaultInstance();
    }

    @java.lang.Override
    public com.shorts.v1alpha1.StateTotal build() {
      com.shorts.v1alpha1.StateTotal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.shorts.v1alpha1.StateTotal buildPartial() {
      com.shorts.v1alpha1.StateTotal result = new com.shorts.v1alpha1.StateTotal(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.shorts.v1alpha1.StateTotal result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.stateCode_ = stateCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.people_ = people_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.companies_ = companies_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.shorts.v1alpha1.StateTotal) {
        return mergeFrom((com.shorts.v1alpha1.StateTotal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.shorts.v1alpha1.StateTotal other) {
      if (other == com.shorts.v1alpha1.StateTotal.getDefaultInstance()) return this;
      if (!other.getStateCode().isEmpty()) {
        stateCode_ = other.stateCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPeople() != 0) {
        setPeople(other.getPeople());
      }
      if (other.getCompanies() != 0) {
        setCompanies(other.getCompanies());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              stateCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              people_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              companies_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object stateCode_ = "";
    /**
     * <code>string state_code = 1 [json_name = "stateCode"];</code>
     * @return The stateCode.
     */
    public java.lang.String getStateCode() {
      java.lang.Object ref = stateCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stateCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state_code = 1 [json_name = "stateCode"];</code>
     * @return The bytes for stateCode.
     */
    public com.google.protobuf.ByteString
        getStateCodeBytes() {
      java.lang.Object ref = stateCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state_code = 1 [json_name = "stateCode"];</code>
     * @param value The stateCode to set.
     * @return This builder for chaining.
     */
    public Builder setStateCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stateCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string state_code = 1 [json_name = "stateCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStateCode() {
      stateCode_ = getDefaultInstance().getStateCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string state_code = 1 [json_name = "stateCode"];</code>
     * @param value The bytes for stateCode to set.
     * @return This builder for chaining.
     */
    public Builder setStateCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stateCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int people_ ;
    /**
     * <code>int32 people = 2 [json_name = "people"];</code>
     * @return The people.
     */
    @java.lang.Override
    public int getPeople() {
      return people_;
    }
    /**
     * <code>int32 people = 2 [json_name = "people"];</code>
     * @param value The people to set.
     * @return This builder for chaining.
     */
    public Builder setPeople(int value) {

      people_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 people = 2 [json_name = "people"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPeople() {
      bitField0_ = (bitField0_ & ~0x00000002);
      people_ = 0;
      onChanged();
      return this;
    }

    private int companies_ ;
    /**
     * <code>int32 companies = 3 [json_name = "companies"];</code>
     * @return The companies.
     */
    @java.lang.Override
    public int getCompanies() {
      return companies_;
    }
    /**
     * <code>int32 companies = 3 [json_name = "companies"];</code>
     * @param value The companies to set.
     * @return This builder for chaining.
     */
    public Builder setCompanies(int value) {

      companies_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 companies = 3 [json_name = "companies"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanies() {
      bitField0_ = (bitField0_ & ~0x00000004);
      companies_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:shorts.v1alpha1.StateTotal)
  }

  // @@protoc_insertion_point(class_scope:shorts.v1alpha1.StateTotal)
  private static final com.shorts.v1alpha1.StateTotal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.shorts.v1alpha1.StateTotal();
  }

  public static com.shorts.v1alpha1.StateTotal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StateTotal>
      PARSER = new com.google.protobuf.AbstractParser<StateTotal>() {
    @java.lang.Override
    public StateTotal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StateTotal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StateTotal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.shorts.v1alpha1.StateTotal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

