// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/stock.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public final class StockProto extends com.google.protobuf.GeneratedFile {
  private StockProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StockProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockPricesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockPricesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockPricesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockPricesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_StockPricePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_StockPricePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockFinancialHighlightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_HighlightsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_HighlightsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_StockFinancialHighlights_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_StockFinancialHighlights_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FinancialReportHighlight_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FinancialReportHighlight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FinancialMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FinancialMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FinancialMetric_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FinancialMetric_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_DirectorTrade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_DirectorTrade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetDirectorTradesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetDirectorTradesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetDirectorTradesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetDirectorTradesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_DividendRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_DividendRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetDividendHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetDividendHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetDividendHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetDividendHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_PeerStock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_PeerStock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetPeerComparisonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetPeerComparisonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetPeerComparisonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetPeerComparisonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockVerdictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockVerdictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_VerdictComponent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_VerdictComponent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockVerdictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockVerdictResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetCompanyTaxProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetCompanyTaxProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_CompanyTaxYear_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_CompanyTaxYear_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetCompanyTaxProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetCompanyTaxProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GraphPerson_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GraphPerson_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GraphPeer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GraphPeer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetEventTimelineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetEventTimelineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetEventTimelineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetEventTimelineResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_TimelineEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_TimelineEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockSignalsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockSignalsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockSignalsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockSignalsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_StockSignal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_StockSignal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockFundamentalsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockFundamentalsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FundamentalsPeriod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FundamentalsPeriod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FundamentalsPeriod_FieldSourcesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FundamentalsPeriod_FieldSourcesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FundamentalsGrowth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FundamentalsGrowth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FundamentalsQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FundamentalsQuality_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_FundamentalsCoverage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_FundamentalsCoverage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_LatestFilingSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shorts_v1alpha1_GetStockFundamentalsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shorts_v1alpha1_GetStockFundamentalsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033shorts/v1alpha1/stock.proto\022\017shorts.v1" +
      "alpha1\032\034stocks/v1alpha1/stocks.proto\032\030op" +
      "tions/v1/options.proto\"4\n\017GetStockReques" +
      "t\022!\n\014product_code\030\001 \001(\tR\013productCode\";\n\026" +
      "GetStockDetailsRequest\022!\n\014product_code\030\001" +
      " \001(\tR\013productCode\"\321\001\n\023GetStockDataReques" +
      "t\022!\n\014product_code\030\001 \001(\tR\013productCode\022\026\n\006" +
      "period\030\002 \001(\tR\006period\022\'\n\017full_resolution\030" +
      "\003 \001(\010R\016fullResolution\022\035\n\nmax_points\030\006 \001(" +
      "\005R\tmaxPoints\022\022\n\004from\030\004 \001(\tR\004from\022\016\n\002to\030\005" +
      " \001(\tR\002to\022\023\n\005as_of\030\007 \001(\tR\004asOf\"\225\001\n\025GetSto" +
      "ckPricesRequest\022!\n\014product_code\030\001 \001(\tR\013p" +
      "roductCode\022\026\n\006period\030\002 \001(\tR\006period\022\022\n\004fr" +
      "om\030\003 \001(\tR\004from\022\016\n\002to\030\004 \001(\tR\002to\022\035\n\nmax_po" +
      "ints\030\005 \001(\005R\tmaxPoints\"\366\001\n\026GetStockPrices" +
      "Response\022!\n\014product_code\030\001 \001(\tR\013productC" +
      "ode\022\022\n\004name\030\002 \001(\tR\004name\0228\n\006points\030\003 \003(\0132" +
      " .shorts.v1alpha1.StockPricePointR\006point" +
      "s\022-\n\022total_observations\030\004 \001(\005R\021totalObse" +
      "rvations\022 \n\013downsampled\030\005 \001(\010R\013downsampl" +
      "ed\022\032\n\010currency\030\006 \001(\tR\010currency\"\264\001\n\017Stock" +
      "PricePoint\022\022\n\004date\030\001 \001(\tR\004date\022\022\n\004open\030\002" +
      " \001(\001R\004open\022\022\n\004high\030\003 \001(\001R\004high\022\020\n\003low\030\004 " +
      "\001(\001R\003low\022\024\n\005close\030\005 \001(\001R\005close\022%\n\016adjust" +
      "ed_close\030\006 \001(\001R\radjustedClose\022\026\n\006volume\030" +
      "\007 \001(\003R\006volume\"x\n\"GetStockFinancialHighli" +
      "ghtsRequest\022\037\n\013stock_codes\030\001 \003(\tR\nstockC" +
      "odes\0221\n\025max_reports_per_stock\030\002 \001(\005R\022max" +
      "ReportsPerStock\"\365\001\n#GetStockFinancialHig" +
      "hlightsResponse\022d\n\nhighlights\030\001 \003(\0132D.sh" +
      "orts.v1alpha1.GetStockFinancialHighlight" +
      "sResponse.HighlightsEntryR\nhighlights\032h\n" +
      "\017HighlightsEntry\022\020\n\003key\030\001 \001(\tR\003key\022?\n\005va" +
      "lue\030\002 \001(\0132).shorts.v1alpha1.StockFinanci" +
      "alHighlightsR\005value:\0028\001\"_\n\030StockFinancia" +
      "lHighlights\022C\n\007reports\030\001 \003(\0132).shorts.v1" +
      "alpha1.FinancialReportHighlightR\007reports" +
      "\"\363\001\n\030FinancialReportHighlight\022!\n\014report_" +
      "title\030\001 \001(\tR\013reportTitle\022\037\n\013report_type\030" +
      "\002 \001(\tR\nreportType\022\037\n\013report_date\030\003 \001(\tR\n" +
      "reportDate\022:\n\007metrics\030\004 \003(\0132 .shorts.v1a" +
      "lpha1.FinancialMetricR\007metrics\022\026\n\006digest" +
      "\030\005 \001(\tR\006digest\022\036\n\nconfidence\030\006 \001(\001R\nconf" +
      "idence\"\344\001\n\017FinancialMetric\022\037\n\013metric_typ" +
      "e\030\001 \001(\tR\nmetricType\022\037\n\013source_text\030\002 \001(\t" +
      "R\nsourceText\022P\n\nattributes\030\003 \003(\01320.short" +
      "s.v1alpha1.FinancialMetric.AttributesEnt" +
      "ryR\nattributes\032=\n\017AttributesEntry\022\020\n\003key" +
      "\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\"\272\002" +
      "\n\rDirectorTrade\022\016\n\002id\030\001 \001(\tR\002id\022\035\n\nstock" +
      "_code\030\002 \001(\tR\tstockCode\022#\n\rdirector_name\030" +
      "\003 \001(\tR\014directorName\022\035\n\ntrade_type\030\004 \001(\tR" +
      "\ttradeType\022#\n\rshares_traded\030\005 \001(\003R\014share" +
      "sTraded\022&\n\017price_per_share\030\006 \001(\001R\rpriceP" +
      "erShare\022\037\n\013total_value\030\007 \001(\001R\ntotalValue" +
      "\022\035\n\ntrade_date\030\010 \001(\tR\ttradeDate\022)\n\020annou" +
      "ncement_url\030\t \001(\tR\017announcementUrl\"O\n\030Ge" +
      "tDirectorTradesRequest\022\035\n\nstock_code\030\001 \001" +
      "(\tR\tstockCode\022\024\n\005limit\030\002 \001(\005R\005limit\"t\n\031G" +
      "etDirectorTradesResponse\0226\n\006trades\030\001 \003(\013" +
      "2\036.shorts.v1alpha1.DirectorTradeR\006trades" +
      "\022\037\n\013total_count\030\002 \001(\005R\ntotalCount\"\373\001\n\016Di" +
      "videndRecord\022\016\n\002id\030\001 \001(\tR\002id\022\035\n\nstock_co" +
      "de\030\002 \001(\tR\tstockCode\022\027\n\007ex_date\030\003 \001(\tR\006ex" +
      "Date\022!\n\014payment_date\030\004 \001(\tR\013paymentDate\022" +
      "(\n\020amount_per_share\030\005 \001(\001R\016amountPerShar" +
      "e\022/\n\023franking_percentage\030\006 \001(\001R\022franking" +
      "Percentage\022#\n\rdividend_type\030\007 \001(\tR\014divid" +
      "endType\"P\n\031GetDividendHistoryRequest\022\035\n\n" +
      "stock_code\030\001 \001(\tR\tstockCode\022\024\n\005years\030\002 \001" +
      "(\005R\005years\"\243\001\n\032GetDividendHistoryResponse" +
      "\022=\n\tdividends\030\001 \003(\0132\037.shorts.v1alpha1.Di" +
      "videndRecordR\tdividends\022\037\n\013total_count\030\002" +
      " \001(\005R\ntotalCount\022%\n\016trailing_yield\030\003 \001(\001" +
      "R\rtrailingYield\"\303\002\n\tPeerStock\022\035\n\nstock_c" +
      "ode\030\001 \001(\tR\tstockCode\022!\n\014company_name\030\002 \001" +
      "(\tR\013companyName\022\032\n\010industry\030\003 \001(\tR\010indus" +
      "try\0224\n\026short_position_percent\030\004 \001(\001R\024sho" +
      "rtPositionPercent\022\035\n\nmarket_cap\030\005 \001(\001R\tm" +
      "arketCap\022\031\n\010pe_ratio\030\006 \001(\001R\007peRatio\022%\n\016d" +
      "ividend_yield\030\007 \001(\001R\rdividendYield\022&\n\017pr" +
      "ice_change_1m\030\010 \001(\001R\rpriceChange1m\022\031\n\010lo" +
      "go_url\030\t \001(\tR\007logoUrl\"O\n\030GetPeerComparis" +
      "onRequest\022\035\n\nstock_code\030\001 \001(\tR\tstockCode" +
      "\022\024\n\005limit\030\002 \001(\005R\005limit\"\237\001\n\031GetPeerCompar" +
      "isonResponse\0224\n\007subject\030\001 \001(\0132\032.shorts.v" +
      "1alpha1.PeerStockR\007subject\0220\n\005peers\030\002 \003(" +
      "\0132\032.shorts.v1alpha1.PeerStockR\005peers\022\032\n\010" +
      "industry\030\003 \001(\tR\010industry\";\n\026GetStockVerd" +
      "ictRequest\022!\n\014product_code\030\001 \001(\tR\013produc" +
      "tCode\"x\n\020VerdictComponent\022\022\n\004name\030\001 \001(\tR" +
      "\004name\022\024\n\005score\030\002 \001(\001R\005score\022\026\n\006weight\030\003 " +
      "\001(\001R\006weight\022\"\n\014contribution\030\004 \001(\001R\014contr" +
      "ibution\"\322\001\n\027GetStockVerdictResponse\022!\n\014p" +
      "roduct_code\030\001 \001(\tR\013productCode\022\034\n\tcompos" +
      "ite\030\002 \001(\001R\tcomposite\0223\n\005label\030\003 \001(\0162\035.sh" +
      "orts.v1alpha1.VerdictLabelR\005label\022A\n\ncom" +
      "ponents\030\004 \003(\0132!.shorts.v1alpha1.VerdictC" +
      "omponentR\ncomponents\"@\n\033GetCompanyTaxPro" +
      "fileRequest\022!\n\014product_code\030\001 \001(\tR\013produ" +
      "ctCode\"\362\001\n\016CompanyTaxYear\022\037\n\013income_year" +
      "\030\001 \001(\005R\nincomeYear\022!\n\014total_income\030\002 \001(\001" +
      "R\013totalIncome\022,\n\022has_taxable_income\030\003 \001(" +
      "\010R\020hasTaxableIncome\022%\n\016taxable_income\030\004 " +
      "\001(\001R\rtaxableIncome\022&\n\017has_tax_payable\030\005 " +
      "\001(\010R\rhasTaxPayable\022\037\n\013tax_payable\030\006 \001(\001R" +
      "\ntaxPayable\"\267\001\n\034GetCompanyTaxProfileResp" +
      "onse\022\037\n\013entity_name\030\001 \001(\tR\nentityName\022\020\n" +
      "\003abn\030\002 \001(\tR\003abn\0225\n\005years\030\003 \003(\0132\037.shorts." +
      "v1alpha1.CompanyTaxYearR\005years\022-\n\022source" +
      "_attribution\030\004 \001(\tR\021sourceAttribution\"K\n" +
      "\024GetStockGraphRequest\022\035\n\nstock_code\030\001 \001(" +
      "\tR\tstockCode\022\024\n\005limit\030\002 \001(\005R\005limit\"\226\001\n\025G" +
      "etStockGraphResponse\0224\n\006people\030\001 \003(\0132\034.s" +
      "horts.v1alpha1.GraphPersonR\006people\022G\n\021si" +
      "milar_companies\030\002 \003(\0132\032.shorts.v1alpha1." +
      "GraphPeerR\020similarCompanies\"\216\001\n\013GraphPer" +
      "son\022\022\n\004name\030\001 \001(\tR\004name\022\022\n\004role\030\002 \001(\tR\004r" +
      "ole\022\033\n\timage_url\030\003 \001(\tR\010imageUrl\022!\n\014link" +
      "edin_url\030\004 \001(\tR\013linkedinUrl\022\027\n\007also_at\030\005" +
      " \003(\tR\006alsoAt\"\211\001\n\tGraphPeer\022\035\n\nstock_code" +
      "\030\001 \001(\tR\tstockCode\022!\n\014company_name\030\002 \001(\tR" +
      "\013companyName\022\032\n\010industry\030\003 \001(\tR\010industry" +
      "\022\036\n\nsimilarity\030\004 \001(\001R\nsimilarity\"k\n\027GetE" +
      "ventTimelineRequest\022\035\n\nstock_code\030\001 \001(\tR" +
      "\tstockCode\022\033\n\tdays_back\030\002 \001(\005R\010daysBack\022" +
      "\024\n\005limit\030\003 \001(\005R\005limit\"R\n\030GetEventTimelin" +
      "eResponse\0226\n\006events\030\001 \003(\0132\036.shorts.v1alp" +
      "ha1.TimelineEventR\006events\"\303\001\n\rTimelineEv" +
      "ent\022\022\n\004date\030\001 \001(\tR\004date\022\022\n\004type\030\002 \001(\tR\004t" +
      "ype\022\024\n\005title\030\003 \001(\tR\005title\022\026\n\006detail\030\004 \001(" +
      "\tR\006detail\022\020\n\003url\030\005 \001(\tR\003url\022\034\n\tsentiment" +
      "\030\006 \001(\tR\tsentiment\022,\n\022is_price_sensitive\030" +
      "\007 \001(\010R\020isPriceSensitive\"M\n\026GetStockSigna" +
      "lsRequest\022\035\n\nstock_code\030\001 \001(\tR\tstockCode" +
      "\022\024\n\005limit\030\002 \001(\005R\005limit\"\213\001\n\027GetStockSigna" +
      "lsResponse\0226\n\007adverse\030\001 \003(\0132\034.shorts.v1a" +
      "lpha1.StockSignalR\007adverse\0228\n\010positive\030\002" +
      " \003(\0132\034.shorts.v1alpha1.StockSignalR\010posi" +
      "tive\"\352\001\n\013StockSignal\022\032\n\010polarity\030\001 \001(\tR\010" +
      "polarity\022\022\n\004kind\030\002 \001(\tR\004kind\022\032\n\010headline" +
      "\030\003 \001(\tR\010headline\022\026\n\006detail\030\004 \001(\tR\006detail" +
      "\022\035\n\nevent_date\030\005 \001(\tR\teventDate\022\032\n\010sever" +
      "ity\030\006 \001(\tR\010severity\022\036\n\nconfidence\030\007 \001(\001R" +
      "\nconfidence\022\034\n\tcitations\030\010 \003(\tR\tcitation" +
      "s\"s\n\033GetStockFundamentalsRequest\022\035\n\nstoc" +
      "k_code\030\001 \001(\tR\tstockCode\022\037\n\013period_type\030\002" +
      " \001(\tR\nperiodType\022\024\n\005limit\030\003 \001(\005R\005limit\"\377" +
      "\025\n\022FundamentalsPeriod\022\037\n\013period_type\030\001 \001" +
      "(\tR\nperiodType\022\035\n\nperiod_end\030\002 \001(\tR\tperi" +
      "odEnd\022\037\n\013fiscal_year\030\003 \001(\005R\nfiscalYear\022\032" +
      "\n\010currency\030\004 \001(\tR\010currency\022\030\n\007revenue\030\005 " +
      "\001(\001R\007revenue\022\037\n\013has_revenue\030\006 \001(\010R\nhasRe" +
      "venue\022\035\n\nnet_income\030\007 \001(\001R\tnetIncome\022$\n\016" +
      "has_net_income\030\010 \001(\010R\014hasNetIncome\022\033\n\tep" +
      "s_basic\030\t \001(\001R\010epsBasic\022\"\n\rhas_eps_basic" +
      "\030\n \001(\010R\013hasEpsBasic\022\037\n\013eps_diluted\030\013 \001(\001" +
      "R\nepsDiluted\022&\n\017has_eps_diluted\030\014 \001(\010R\rh" +
      "asEpsDiluted\022.\n\023operating_cash_flow\030\r \001(" +
      "\001R\021operatingCashFlow\0225\n\027has_operating_ca" +
      "sh_flow\030\016 \001(\010R\024hasOperatingCashFlow\022-\n\022s" +
      "hares_outstanding\030\017 \001(\001R\021sharesOutstandi" +
      "ng\0224\n\026has_shares_outstanding\030\020 \001(\010R\024hasS" +
      "haresOutstanding\022\026\n\006source\030\021 \001(\tR\006source" +
      "\022\035\n\nfetched_at\030\022 \001(\tR\tfetchedAt\022$\n\016free_" +
      "cash_flow\030\023 \001(\001R\014freeCashFlow\022+\n\022has_fre" +
      "e_cash_flow\030\024 \001(\010R\017hasFreeCashFlow\022!\n\014gr" +
      "oss_profit\030\025 \001(\001R\013grossProfit\022(\n\020has_gro" +
      "ss_profit\030\026 \001(\010R\016hasGrossProfit\022)\n\020opera" +
      "ting_income\030\027 \001(\001R\017operatingIncome\0220\n\024ha" +
      "s_operating_income\030\030 \001(\010R\022hasOperatingIn" +
      "come\022\026\n\006ebitda\030\031 \001(\001R\006ebitda\022\035\n\nhas_ebit" +
      "da\030\032 \001(\010R\thasEbitda\022+\n\021normalized_ebitda" +
      "\030\033 \001(\001R\020normalizedEbitda\0222\n\025has_normaliz" +
      "ed_ebitda\030\034 \001(\010R\023hasNormalizedEbitda\022\022\n\004" +
      "ebit\030\035 \001(\001R\004ebit\022\031\n\010has_ebit\030\036 \001(\010R\007hasE" +
      "bit\022)\n\020interest_expense\030\037 \001(\001R\017interestE" +
      "xpense\0220\n\024has_interest_expense\030  \001(\010R\022ha" +
      "sInterestExpense\022#\n\rpretax_income\030! \001(\001R" +
      "\014pretaxIncome\022*\n\021has_pretax_income\030\" \001(\010" +
      "R\017hasPretaxIncome\022#\n\rtax_provision\030# \001(\001" +
      "R\014taxProvision\022*\n\021has_tax_provision\030$ \001(" +
      "\010R\017hasTaxProvision\022.\n\023net_interest_incom" +
      "e\030% \001(\001R\021netInterestIncome\0225\n\027has_net_in" +
      "terest_income\030& \001(\010R\024hasNetInterestIncom" +
      "e\022/\n\023capital_expenditure\030\' \001(\001R\022capitalE" +
      "xpenditure\0226\n\027has_capital_expenditure\030( " +
      "\001(\010R\025hasCapitalExpenditure\022%\n\016dividends_" +
      "paid\030) \001(\001R\rdividendsPaid\022,\n\022has_dividen" +
      "ds_paid\030* \001(\010R\020hasDividendsPaid\022%\n\016share" +
      "_buybacks\030+ \001(\001R\rshareBuybacks\022,\n\022has_sh" +
      "are_buybacks\030, \001(\010R\020hasShareBuybacks\022!\n\014" +
      "total_assets\030- \001(\001R\013totalAssets\022(\n\020has_t" +
      "otal_assets\030. \001(\010R\016hasTotalAssets\022+\n\021tot" +
      "al_liabilities\030/ \001(\001R\020totalLiabilities\0222" +
      "\n\025has_total_liabilities\0300 \001(\010R\023hasTotalL" +
      "iabilities\022!\n\014total_equity\0301 \001(\001R\013totalE" +
      "quity\022(\n\020has_total_equity\0302 \001(\010R\016hasTota" +
      "lEquity\0220\n\024cash_and_equivalents\0303 \001(\001R\022c" +
      "ashAndEquivalents\0227\n\030has_cash_and_equiva" +
      "lents\0304 \001(\010R\025hasCashAndEquivalents\022\035\n\nto" +
      "tal_debt\0305 \001(\001R\ttotalDebt\022$\n\016has_total_d" +
      "ebt\0306 \001(\010R\014hasTotalDebt\022:\n\031capital_lease" +
      "_obligations\0307 \001(\001R\027capitalLeaseObligati" +
      "ons\022A\n\035has_capital_lease_obligations\0308 \001" +
      "(\010R\032hasCapitalLeaseObligations\022\031\n\010net_de" +
      "bt\0309 \001(\001R\007netDebt\022 \n\014has_net_debt\030: \001(\010R" +
      "\nhasNetDebt\022%\n\016current_assets\030; \001(\001R\rcur" +
      "rentAssets\022,\n\022has_current_assets\030< \001(\010R\020" +
      "hasCurrentAssets\022/\n\023current_liabilities\030" +
      "= \001(\001R\022currentLiabilities\0226\n\027has_current" +
      "_liabilities\030> \001(\010R\025hasCurrentLiabilitie" +
      "s\022Z\n\rfield_sources\030? \003(\01325.shorts.v1alph" +
      "a1.FundamentalsPeriod.FieldSourcesEntryR" +
      "\014fieldSources\022.\n\023source_document_url\030@ \001" +
      "(\tR\021sourceDocumentUrl\0220\n\024source_document" +
      "_date\030A \001(\tR\022sourceDocumentDate\032?\n\021Field" +
      "SourcesEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030" +
      "\002 \001(\tR\005value:\0028\001\"\375\t\n\022FundamentalsGrowth\022" +
      "*\n\021basis_period_type\030\001 \001(\tR\017basisPeriodT" +
      "ype\022*\n\021latest_period_end\030\002 \001(\tR\017latestPe" +
      "riodEnd\022&\n\017revenue_yoy_pct\030\003 \001(\001R\rrevenu" +
      "eYoyPct\022&\n\017has_revenue_yoy\030\004 \001(\010R\rhasRev" +
      "enueYoy\0221\n\025revenue_yoy_prior_pct\030\005 \001(\001R\022" +
      "revenueYoyPriorPct\0221\n\025has_revenue_yoy_pr" +
      "ior\030\006 \001(\010R\022hasRevenueYoyPrior\022\036\n\013eps_yoy" +
      "_pct\030\007 \001(\001R\tepsYoyPct\022\036\n\013has_eps_yoy\030\010 \001" +
      "(\010R\thasEpsYoy\022)\n\021eps_yoy_prior_pct\030\t \001(\001" +
      "R\016epsYoyPriorPct\022)\n\021has_eps_yoy_prior\030\n " +
      "\001(\010R\016hasEpsYoyPrior\022.\n\023net_income_positi" +
      "ve\030\013 \001(\010R\021netIncomePositive\022+\n\021periods_a" +
      "vailable\030\014 \001(\005R\020periodsAvailable\022\037\n\013reve" +
      "nue_ttm\030\r \001(\001R\nrevenueTtm\022&\n\017has_revenue" +
      "_ttm\030\016 \001(\010R\rhasRevenueTtm\022$\n\016net_income_" +
      "ttm\030\017 \001(\001R\014netIncomeTtm\022+\n\022has_net_incom" +
      "e_ttm\030\020 \001(\010R\017hasNetIncomeTtm\022\027\n\007eps_ttm\030" +
      "\021 \001(\001R\006epsTtm\022\036\n\013has_eps_ttm\030\022 \001(\010R\thasE" +
      "psTtm\0229\n\031revenue_basis_period_type\030\023 \001(\t" +
      "R\026revenueBasisPeriodType\022/\n\024revenue_half" +
      "_yoy_pct\030\024 \001(\001R\021revenueHalfYoyPct\022/\n\024has" +
      "_revenue_half_yoy\030\025 \001(\010R\021hasRevenueHalfY" +
      "oy\022\'\n\020eps_half_yoy_pct\030\026 \001(\001R\repsHalfYoy" +
      "Pct\022\'\n\020has_eps_half_yoy\030\027 \001(\010R\rhasEpsHal" +
      "fYoy\0223\n\026half_latest_period_end\030\030 \001(\tR\023ha" +
      "lfLatestPeriodEnd\0220\n\024revenue_basis_sourc" +
      "e\030\031 \001(\tR\022revenueBasisSource\022(\n\020eps_basis" +
      "_source\030\032 \001(\tR\016epsBasisSource\022\035\n\nfetched" +
      "_at\030\033 \001(\tR\tfetchedAt\0229\n\031revenue_latest_p" +
      "eriod_end\030\034 \001(\tR\026revenueLatestPeriodEnd\022" +
      "7\n\030revenue_prior_period_end\030\035 \001(\tR\025reven" +
      "uePriorPeriodEnd\"\212\017\n\023FundamentalsQuality" +
      "\022*\n\021basis_period_type\030\001 \001(\tR\017basisPeriod" +
      "Type\022(\n\020basis_period_end\030\002 \001(\tR\016basisPer" +
      "iodEnd\022\032\n\010currency\030\003 \001(\tR\010currency\022,\n\022ba" +
      "lance_period_end\030\004 \001(\tR\020balancePeriodEnd" +
      "\022(\n\020gross_margin_pct\030\005 \001(\001R\016grossMarginP" +
      "ct\022/\n\024has_gross_margin_pct\030\006 \001(\010R\021hasGro" +
      "ssMarginPct\0220\n\024operating_margin_pct\030\007 \001(" +
      "\001R\022operatingMarginPct\0227\n\030has_operating_m" +
      "argin_pct\030\010 \001(\010R\025hasOperatingMarginPct\022$" +
      "\n\016net_margin_pct\030\t \001(\001R\014netMarginPct\022+\n\022" +
      "has_net_margin_pct\030\n \001(\010R\017hasNetMarginPc" +
      "t\022$\n\016fcf_margin_pct\030\013 \001(\001R\014fcfMarginPct\022" +
      "+\n\022has_fcf_margin_pct\030\014 \001(\010R\017hasFcfMargi" +
      "nPct\022%\n\016fcf_conversion\030\r \001(\001R\rfcfConvers" +
      "ion\022,\n\022has_fcf_conversion\030\016 \001(\010R\020hasFcfC" +
      "onversion\022\027\n\007roe_pct\030\017 \001(\001R\006roePct\022\036\n\013ha" +
      "s_roe_pct\030\020 \001(\010R\thasRoePct\022\027\n\007roa_pct\030\021 " +
      "\001(\001R\006roaPct\022\036\n\013has_roa_pct\030\022 \001(\010R\thasRoa" +
      "Pct\022\031\n\010net_debt\030\023 \001(\001R\007netDebt\022 \n\014has_ne" +
      "t_debt\030\024 \001(\010R\nhasNetDebt\022+\n\022net_debt_to_" +
      "ebitda\030\025 \001(\001R\017netDebtToEbitda\0222\n\026has_net" +
      "_debt_to_ebitda\030\026 \001(\010R\022hasNetDebtToEbitd" +
      "a\022+\n\022net_debt_to_equity\030\027 \001(\001R\017netDebtTo" +
      "Equity\0222\n\026has_net_debt_to_equity\030\030 \001(\010R\022" +
      "hasNetDebtToEquity\022#\n\rcurrent_ratio\030\031 \001(" +
      "\001R\014currentRatio\022*\n\021has_current_ratio\030\032 \001" +
      "(\010R\017hasCurrentRatio\022%\n\016interest_cover\030\033 " +
      "\001(\001R\rinterestCover\022,\n\022has_interest_cover" +
      "\030\034 \001(\010R\020hasInterestCover\022(\n\020payout_ratio" +
      "_pct\030\035 \001(\001R\016payoutRatioPct\022/\n\024has_payout" +
      "_ratio_pct\030\036 \001(\010R\021hasPayoutRatioPct\022!\n\014i" +
      "s_financial\030\037 \001(\010R\013isFinancial\022\026\n\006source" +
      "\030  \001(\tR\006source\022=\n\033operating_cash_flow_de" +
      "rived\030! \001(\010R\030operatingCashFlowDerived\022\035\n" +
      "\nmarket_cap\030\" \001(\001R\tmarketCap\022$\n\016has_mark" +
      "et_cap\030# \001(\010R\014hasMarketCap\022\031\n\010pe_ratio\030$" +
      " \001(\001R\007peRatio\022 \n\014has_pe_ratio\030% \001(\010R\nhas" +
      "PeRatio\022\"\n\rprice_to_book\030& \001(\001R\013priceToB" +
      "ook\022)\n\021has_price_to_book\030\' \001(\010R\016hasPrice" +
      "ToBook\022\036\n\013price_as_of\030( \001(\tR\tpriceAsOf\022)" +
      "\n\020balance_currency\030) \001(\tR\017balanceCurrenc" +
      "y\022%\n\016not_meaningful\030* \003(\tR\rnotMeaningful" +
      "\022\037\n\013is_property\030+ \001(\010R\nisProperty\022,\n\022bal" +
      "ance_lag_months\030, \001(\005R\020balanceLagMonths\022" +
      " \n\014shares_as_of\030- \001(\tR\nsharesAsOf\022)\n\021pe_" +
      "eps_period_end\030. \001(\tR\016peEpsPeriodEnd\022 \n\014" +
      "pe_eps_basis\030/ \001(\tR\npeEpsBasis\022%\n\016valuat" +
      "ion_note\0300 \001(\tR\rvaluationNote\"\230\001\n\024Fundam" +
      "entalsCoverage\022\026\n\006status\030\001 \001(\tR\006status\022&" +
      "\n\017last_attempt_at\030\002 \001(\tR\rlastAttemptAt\022&" +
      "\n\017last_success_at\030\003 \001(\tR\rlastSuccessAt\022\030" +
      "\n\007sources\030\004 \003(\tR\007sources\"\375\001\n\023LatestFilin" +
      "gSummary\022\035\n\nreport_url\030\001 \001(\tR\treportUrl\022" +
      "!\n\014report_title\030\002 \001(\tR\013reportTitle\022\037\n\013re" +
      "port_date\030\003 \001(\tR\nreportDate\022\035\n\nperiod_en" +
      "d\030\004 \001(\tR\tperiodEnd\022\037\n\013period_type\030\005 \001(\tR" +
      "\nperiodType\022\026\n\006digest\030\006 \001(\tR\006digest\022+\n\021d" +
      "igest_confidence\030\007 \001(\001R\020digestConfidence" +
      "\"\363\003\n\034GetStockFundamentalsResponse\022\035\n\nsto" +
      "ck_code\030\001 \001(\tR\tstockCode\022=\n\007periods\030\002 \003(" +
      "\0132#.shorts.v1alpha1.FundamentalsPeriodR\007" +
      "periods\022;\n\006growth\030\003 \001(\0132#.shorts.v1alpha" +
      "1.FundamentalsGrowthR\006growth\022\035\n\nhas_grow" +
      "th\030\004 \001(\010R\thasGrowth\022>\n\007quality\030\005 \001(\0132$.s" +
      "horts.v1alpha1.FundamentalsQualityR\007qual" +
      "ity\022\037\n\013has_quality\030\006 \001(\010R\nhasQuality\022A\n\010" +
      "coverage\030\007 \001(\0132%.shorts.v1alpha1.Fundame" +
      "ntalsCoverageR\010coverage\022I\n\rlatest_filing" +
      "\030\010 \001(\0132$.shorts.v1alpha1.LatestFilingSum" +
      "maryR\014latestFiling\022*\n\021has_latest_filing\030" +
      "\t \001(\010R\017hasLatestFiling*\302\001\n\014VerdictLabel\022" +
      "\035\n\031VERDICT_LABEL_UNSPECIFIED\020\000\022 \n\034VERDIC" +
      "T_LABEL_STRONG_BEARISH\020\001\022\031\n\025VERDICT_LABE" +
      "L_BEARISH\020\002\022\031\n\025VERDICT_LABEL_NEUTRAL\020\003\022\031" +
      "\n\025VERDICT_LABEL_BULLISH\020\004\022 \n\034VERDICT_LAB" +
      "EL_STRONG_BULLISH\020\0052\216\014\n\014StockService\022J\n\010" +
      "GetStock\022 .shorts.v1alpha1.GetStockReque" +
      "st\032\026.stocks.v1alpha1.Stock\"\004\200\265\030\001\022_\n\017GetS" +
      "tockDetails\022\'.shorts.v1alpha1.GetStockDe" +
      "tailsRequest\032\035.stocks.v1alpha1.StockDeta" +
      "ils\"\004\200\265\030\001\022[\n\014GetStockData\022$.shorts.v1alp" +
      "ha1.GetStockDataRequest\032\037.stocks.v1alpha" +
      "1.TimeSeriesData\"\004\200\265\030\001\022g\n\016GetStockPrices" +
      "\022&.shorts.v1alpha1.GetStockPricesRequest" +
      "\032\'.shorts.v1alpha1.GetStockPricesRespons" +
      "e\"\004\200\265\030\001\022\216\001\n\033GetStockFinancialHighlights\022" +
      "3.shorts.v1alpha1.GetStockFinancialHighl" +
      "ightsRequest\0324.shorts.v1alpha1.GetStockF" +
      "inancialHighlightsResponse\"\004\200\265\030\001\022p\n\021GetD" +
      "irectorTrades\022).shorts.v1alpha1.GetDirec" +
      "torTradesRequest\032*.shorts.v1alpha1.GetDi" +
      "rectorTradesResponse\"\004\200\265\030\001\022s\n\022GetDividen" +
      "dHistory\022*.shorts.v1alpha1.GetDividendHi" +
      "storyRequest\032+.shorts.v1alpha1.GetDivide" +
      "ndHistoryResponse\"\004\200\265\030\001\022p\n\021GetPeerCompar" +
      "ison\022).shorts.v1alpha1.GetPeerComparison" +
      "Request\032*.shorts.v1alpha1.GetPeerCompari" +
      "sonResponse\"\004\200\265\030\001\022j\n\017GetStockVerdict\022\'.s" +
      "horts.v1alpha1.GetStockVerdictRequest\032(." +
      "shorts.v1alpha1.GetStockVerdictResponse\"" +
      "\004\200\265\030\001\022d\n\rGetStockGraph\022%.shorts.v1alpha1" +
      ".GetStockGraphRequest\032&.shorts.v1alpha1." +
      "GetStockGraphResponse\"\004\200\265\030\001\022m\n\020GetEventT" +
      "imeline\022(.shorts.v1alpha1.GetEventTimeli" +
      "neRequest\032).shorts.v1alpha1.GetEventTime" +
      "lineResponse\"\004\200\265\030\001\022j\n\017GetStockSignals\022\'." +
      "shorts.v1alpha1.GetStockSignalsRequest\032(" +
      ".shorts.v1alpha1.GetStockSignalsResponse" +
      "\"\004\200\265\030\001\022y\n\024GetCompanyTaxProfile\022,.shorts." +
      "v1alpha1.GetCompanyTaxProfileRequest\032-.s" +
      "horts.v1alpha1.GetCompanyTaxProfileRespo" +
      "nse\"\004\200\265\030\001\022y\n\024GetStockFundamentals\022,.shor" +
      "ts.v1alpha1.GetStockFundamentalsRequest\032" +
      "-.shorts.v1alpha1.GetStockFundamentalsRe" +
      "sponse\"\004\200\265\030\001B\331\001\n\023com.shorts.v1alpha1B\nSt" +
      "ockProtoP\001ZYgithub.com/castlemilk/shorte" +
      "d.com.au/services/gen/proto/go/shorts/v1" +
      "alpha1;shortsv1alpha1\242\002\003SXX\252\002\017Shorts.V1a" +
      "lpha1\312\002\017Shorts\\V1alpha1\342\002\033Shorts\\V1alpha" +
      "1\\GPBMetadata\352\002\020Shorts::V1alpha1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stocks.v1alpha1.StocksProto.getDescriptor(),
          com.shortedapi.options.v1.OptionsProto.getDescriptor(),
        });
    internal_static_shorts_v1alpha1_GetStockRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_shorts_v1alpha1_GetStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockRequest_descriptor,
        new java.lang.String[] { "ProductCode", });
    internal_static_shorts_v1alpha1_GetStockDetailsRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_shorts_v1alpha1_GetStockDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockDetailsRequest_descriptor,
        new java.lang.String[] { "ProductCode", });
    internal_static_shorts_v1alpha1_GetStockDataRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_shorts_v1alpha1_GetStockDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockDataRequest_descriptor,
        new java.lang.String[] { "ProductCode", "Period", "FullResolution", "MaxPoints", "From", "To", "AsOf", });
    internal_static_shorts_v1alpha1_GetStockPricesRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_shorts_v1alpha1_GetStockPricesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockPricesRequest_descriptor,
        new java.lang.String[] { "ProductCode", "Period", "From", "To", "MaxPoints", });
    internal_static_shorts_v1alpha1_GetStockPricesResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_shorts_v1alpha1_GetStockPricesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockPricesResponse_descriptor,
        new java.lang.String[] { "ProductCode", "Name", "Points", "TotalObservations", "Downsampled", "Currency", });
    internal_static_shorts_v1alpha1_StockPricePoint_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_shorts_v1alpha1_StockPricePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_StockPricePoint_descriptor,
        new java.lang.String[] { "Date", "Open", "High", "Low", "Close", "AdjustedClose", "Volume", });
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockFinancialHighlightsRequest_descriptor,
        new java.lang.String[] { "StockCodes", "MaxReportsPerStock", });
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_descriptor,
        new java.lang.String[] { "Highlights", });
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_HighlightsEntry_descriptor =
      internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_descriptor.getNestedType(0);
    internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_HighlightsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockFinancialHighlightsResponse_HighlightsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_shorts_v1alpha1_StockFinancialHighlights_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_shorts_v1alpha1_StockFinancialHighlights_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_StockFinancialHighlights_descriptor,
        new java.lang.String[] { "Reports", });
    internal_static_shorts_v1alpha1_FinancialReportHighlight_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_shorts_v1alpha1_FinancialReportHighlight_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FinancialReportHighlight_descriptor,
        new java.lang.String[] { "ReportTitle", "ReportType", "ReportDate", "Metrics", "Digest", "Confidence", });
    internal_static_shorts_v1alpha1_FinancialMetric_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_shorts_v1alpha1_FinancialMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FinancialMetric_descriptor,
        new java.lang.String[] { "MetricType", "SourceText", "Attributes", });
    internal_static_shorts_v1alpha1_FinancialMetric_AttributesEntry_descriptor =
      internal_static_shorts_v1alpha1_FinancialMetric_descriptor.getNestedType(0);
    internal_static_shorts_v1alpha1_FinancialMetric_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FinancialMetric_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_shorts_v1alpha1_DirectorTrade_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_shorts_v1alpha1_DirectorTrade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_DirectorTrade_descriptor,
        new java.lang.String[] { "Id", "StockCode", "DirectorName", "TradeType", "SharesTraded", "PricePerShare", "TotalValue", "TradeDate", "AnnouncementUrl", });
    internal_static_shorts_v1alpha1_GetDirectorTradesRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_shorts_v1alpha1_GetDirectorTradesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetDirectorTradesRequest_descriptor,
        new java.lang.String[] { "StockCode", "Limit", });
    internal_static_shorts_v1alpha1_GetDirectorTradesResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_shorts_v1alpha1_GetDirectorTradesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetDirectorTradesResponse_descriptor,
        new java.lang.String[] { "Trades", "TotalCount", });
    internal_static_shorts_v1alpha1_DividendRecord_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_shorts_v1alpha1_DividendRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_DividendRecord_descriptor,
        new java.lang.String[] { "Id", "StockCode", "ExDate", "PaymentDate", "AmountPerShare", "FrankingPercentage", "DividendType", });
    internal_static_shorts_v1alpha1_GetDividendHistoryRequest_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_shorts_v1alpha1_GetDividendHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetDividendHistoryRequest_descriptor,
        new java.lang.String[] { "StockCode", "Years", });
    internal_static_shorts_v1alpha1_GetDividendHistoryResponse_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_shorts_v1alpha1_GetDividendHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetDividendHistoryResponse_descriptor,
        new java.lang.String[] { "Dividends", "TotalCount", "TrailingYield", });
    internal_static_shorts_v1alpha1_PeerStock_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_shorts_v1alpha1_PeerStock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_PeerStock_descriptor,
        new java.lang.String[] { "StockCode", "CompanyName", "Industry", "ShortPositionPercent", "MarketCap", "PeRatio", "DividendYield", "PriceChange1M", "LogoUrl", });
    internal_static_shorts_v1alpha1_GetPeerComparisonRequest_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_shorts_v1alpha1_GetPeerComparisonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetPeerComparisonRequest_descriptor,
        new java.lang.String[] { "StockCode", "Limit", });
    internal_static_shorts_v1alpha1_GetPeerComparisonResponse_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_shorts_v1alpha1_GetPeerComparisonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetPeerComparisonResponse_descriptor,
        new java.lang.String[] { "Subject", "Peers", "Industry", });
    internal_static_shorts_v1alpha1_GetStockVerdictRequest_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_shorts_v1alpha1_GetStockVerdictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockVerdictRequest_descriptor,
        new java.lang.String[] { "ProductCode", });
    internal_static_shorts_v1alpha1_VerdictComponent_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_shorts_v1alpha1_VerdictComponent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_VerdictComponent_descriptor,
        new java.lang.String[] { "Name", "Score", "Weight", "Contribution", });
    internal_static_shorts_v1alpha1_GetStockVerdictResponse_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_shorts_v1alpha1_GetStockVerdictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockVerdictResponse_descriptor,
        new java.lang.String[] { "ProductCode", "Composite", "Label", "Components", });
    internal_static_shorts_v1alpha1_GetCompanyTaxProfileRequest_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_shorts_v1alpha1_GetCompanyTaxProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetCompanyTaxProfileRequest_descriptor,
        new java.lang.String[] { "ProductCode", });
    internal_static_shorts_v1alpha1_CompanyTaxYear_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_shorts_v1alpha1_CompanyTaxYear_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_CompanyTaxYear_descriptor,
        new java.lang.String[] { "IncomeYear", "TotalIncome", "HasTaxableIncome", "TaxableIncome", "HasTaxPayable", "TaxPayable", });
    internal_static_shorts_v1alpha1_GetCompanyTaxProfileResponse_descriptor =
      getDescriptor().getMessageType(25);
    internal_static_shorts_v1alpha1_GetCompanyTaxProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetCompanyTaxProfileResponse_descriptor,
        new java.lang.String[] { "EntityName", "Abn", "Years", "SourceAttribution", });
    internal_static_shorts_v1alpha1_GetStockGraphRequest_descriptor =
      getDescriptor().getMessageType(26);
    internal_static_shorts_v1alpha1_GetStockGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockGraphRequest_descriptor,
        new java.lang.String[] { "StockCode", "Limit", });
    internal_static_shorts_v1alpha1_GetStockGraphResponse_descriptor =
      getDescriptor().getMessageType(27);
    internal_static_shorts_v1alpha1_GetStockGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockGraphResponse_descriptor,
        new java.lang.String[] { "People", "SimilarCompanies", });
    internal_static_shorts_v1alpha1_GraphPerson_descriptor =
      getDescriptor().getMessageType(28);
    internal_static_shorts_v1alpha1_GraphPerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GraphPerson_descriptor,
        new java.lang.String[] { "Name", "Role", "ImageUrl", "LinkedinUrl", "AlsoAt", });
    internal_static_shorts_v1alpha1_GraphPeer_descriptor =
      getDescriptor().getMessageType(29);
    internal_static_shorts_v1alpha1_GraphPeer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GraphPeer_descriptor,
        new java.lang.String[] { "StockCode", "CompanyName", "Industry", "Similarity", });
    internal_static_shorts_v1alpha1_GetEventTimelineRequest_descriptor =
      getDescriptor().getMessageType(30);
    internal_static_shorts_v1alpha1_GetEventTimelineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetEventTimelineRequest_descriptor,
        new java.lang.String[] { "StockCode", "DaysBack", "Limit", });
    internal_static_shorts_v1alpha1_GetEventTimelineResponse_descriptor =
      getDescriptor().getMessageType(31);
    internal_static_shorts_v1alpha1_GetEventTimelineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetEventTimelineResponse_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_shorts_v1alpha1_TimelineEvent_descriptor =
      getDescriptor().getMessageType(32);
    internal_static_shorts_v1alpha1_TimelineEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_TimelineEvent_descriptor,
        new java.lang.String[] { "Date", "Type", "Title", "Detail", "Url", "Sentiment", "IsPriceSensitive", });
    internal_static_shorts_v1alpha1_GetStockSignalsRequest_descriptor =
      getDescriptor().getMessageType(33);
    internal_static_shorts_v1alpha1_GetStockSignalsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockSignalsRequest_descriptor,
        new java.lang.String[] { "StockCode", "Limit", });
    internal_static_shorts_v1alpha1_GetStockSignalsResponse_descriptor =
      getDescriptor().getMessageType(34);
    internal_static_shorts_v1alpha1_GetStockSignalsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockSignalsResponse_descriptor,
        new java.lang.String[] { "Adverse", "Positive", });
    internal_static_shorts_v1alpha1_StockSignal_descriptor =
      getDescriptor().getMessageType(35);
    internal_static_shorts_v1alpha1_StockSignal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_StockSignal_descriptor,
        new java.lang.String[] { "Polarity", "Kind", "Headline", "Detail", "EventDate", "Severity", "Confidence", "Citations", });
    internal_static_shorts_v1alpha1_GetStockFundamentalsRequest_descriptor =
      getDescriptor().getMessageType(36);
    internal_static_shorts_v1alpha1_GetStockFundamentalsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockFundamentalsRequest_descriptor,
        new java.lang.String[] { "StockCode", "PeriodType", "Limit", });
    internal_static_shorts_v1alpha1_FundamentalsPeriod_descriptor =
      getDescriptor().getMessageType(37);
    internal_static_shorts_v1alpha1_FundamentalsPeriod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FundamentalsPeriod_descriptor,
        new java.lang.String[] { "PeriodType", "PeriodEnd", "FiscalYear", "Currency", "Revenue", "HasRevenue", "NetIncome", "HasNetIncome", "EpsBasic", "HasEpsBasic", "EpsDiluted", "HasEpsDiluted", "OperatingCashFlow", "HasOperatingCashFlow", "SharesOutstanding", "HasSharesOutstanding", "Source", "FetchedAt", "FreeCashFlow", "HasFreeCashFlow", "GrossProfit", "HasGrossProfit", "OperatingIncome", "HasOperatingIncome", "Ebitda", "HasEbitda", "NormalizedEbitda", "HasNormalizedEbitda", "Ebit", "HasEbit", "InterestExpense", "HasInterestExpense", "PretaxIncome", "HasPretaxIncome", "TaxProvision", "HasTaxProvision", "NetInterestIncome", "HasNetInterestIncome", "CapitalExpenditure", "HasCapitalExpenditure", "DividendsPaid", "HasDividendsPaid", "ShareBuybacks", "HasShareBuybacks", "TotalAssets", "HasTotalAssets", "TotalLiabilities", "HasTotalLiabilities", "TotalEquity", "HasTotalEquity", "CashAndEquivalents", "HasCashAndEquivalents", "TotalDebt", "HasTotalDebt", "CapitalLeaseObligations", "HasCapitalLeaseObligations", "NetDebt", "HasNetDebt", "CurrentAssets", "HasCurrentAssets", "CurrentLiabilities", "HasCurrentLiabilities", "FieldSources", "SourceDocumentUrl", "SourceDocumentDate", });
    internal_static_shorts_v1alpha1_FundamentalsPeriod_FieldSourcesEntry_descriptor =
      internal_static_shorts_v1alpha1_FundamentalsPeriod_descriptor.getNestedType(0);
    internal_static_shorts_v1alpha1_FundamentalsPeriod_FieldSourcesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FundamentalsPeriod_FieldSourcesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_shorts_v1alpha1_FundamentalsGrowth_descriptor =
      getDescriptor().getMessageType(38);
    internal_static_shorts_v1alpha1_FundamentalsGrowth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FundamentalsGrowth_descriptor,
        new java.lang.String[] { "BasisPeriodType", "LatestPeriodEnd", "RevenueYoyPct", "HasRevenueYoy", "RevenueYoyPriorPct", "HasRevenueYoyPrior", "EpsYoyPct", "HasEpsYoy", "EpsYoyPriorPct", "HasEpsYoyPrior", "NetIncomePositive", "PeriodsAvailable", "RevenueTtm", "HasRevenueTtm", "NetIncomeTtm", "HasNetIncomeTtm", "EpsTtm", "HasEpsTtm", "RevenueBasisPeriodType", "RevenueHalfYoyPct", "HasRevenueHalfYoy", "EpsHalfYoyPct", "HasEpsHalfYoy", "HalfLatestPeriodEnd", "RevenueBasisSource", "EpsBasisSource", "FetchedAt", "RevenueLatestPeriodEnd", "RevenuePriorPeriodEnd", });
    internal_static_shorts_v1alpha1_FundamentalsQuality_descriptor =
      getDescriptor().getMessageType(39);
    internal_static_shorts_v1alpha1_FundamentalsQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FundamentalsQuality_descriptor,
        new java.lang.String[] { "BasisPeriodType", "BasisPeriodEnd", "Currency", "BalancePeriodEnd", "GrossMarginPct", "HasGrossMarginPct", "OperatingMarginPct", "HasOperatingMarginPct", "NetMarginPct", "HasNetMarginPct", "FcfMarginPct", "HasFcfMarginPct", "FcfConversion", "HasFcfConversion", "RoePct", "HasRoePct", "RoaPct", "HasRoaPct", "NetDebt", "HasNetDebt", "NetDebtToEbitda", "HasNetDebtToEbitda", "NetDebtToEquity", "HasNetDebtToEquity", "CurrentRatio", "HasCurrentRatio", "InterestCover", "HasInterestCover", "PayoutRatioPct", "HasPayoutRatioPct", "IsFinancial", "Source", "OperatingCashFlowDerived", "MarketCap", "HasMarketCap", "PeRatio", "HasPeRatio", "PriceToBook", "HasPriceToBook", "PriceAsOf", "BalanceCurrency", "NotMeaningful", "IsProperty", "BalanceLagMonths", "SharesAsOf", "PeEpsPeriodEnd", "PeEpsBasis", "ValuationNote", });
    internal_static_shorts_v1alpha1_FundamentalsCoverage_descriptor =
      getDescriptor().getMessageType(40);
    internal_static_shorts_v1alpha1_FundamentalsCoverage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_FundamentalsCoverage_descriptor,
        new java.lang.String[] { "Status", "LastAttemptAt", "LastSuccessAt", "Sources", });
    internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor =
      getDescriptor().getMessageType(41);
    internal_static_shorts_v1alpha1_LatestFilingSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_LatestFilingSummary_descriptor,
        new java.lang.String[] { "ReportUrl", "ReportTitle", "ReportDate", "PeriodEnd", "PeriodType", "Digest", "DigestConfidence", });
    internal_static_shorts_v1alpha1_GetStockFundamentalsResponse_descriptor =
      getDescriptor().getMessageType(42);
    internal_static_shorts_v1alpha1_GetStockFundamentalsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shorts_v1alpha1_GetStockFundamentalsResponse_descriptor,
        new java.lang.String[] { "StockCode", "Periods", "Growth", "HasGrowth", "Quality", "HasQuality", "Coverage", "LatestFiling", "HasLatestFiling", });
    descriptor.resolveAllFeaturesImmutable();
    com.stocks.v1alpha1.StocksProto.getDescriptor();
    com.shortedapi.options.v1.OptionsProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.shortedapi.options.v1.OptionsProto.visibility);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
