// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shorts/v1alpha1/shorts.proto
// Protobuf Java Version: 4.35.1

package com.shorts.v1alpha1;

@com.google.protobuf.Generated
public interface WeeklyReportFAQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shorts.v1alpha1.WeeklyReportFAQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string question = 1 [json_name = "question"];</code>
   * @return The question.
   */
  java.lang.String getQuestion();
  /**
   * <code>string question = 1 [json_name = "question"];</code>
   * @return The bytes for question.
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <code>string answer = 2 [json_name = "answer"];</code>
   * @return The answer.
   */
  java.lang.String getAnswer();
  /**
   * <code>string answer = 2 [json_name = "answer"];</code>
   * @return The bytes for answer.
   */
  com.google.protobuf.ByteString
      getAnswerBytes();
}
