# Cloud Build configuration for deploying stock price ingestion service
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stock-price-ingestion:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/stock-price-ingestion:latest"
      - "."
    dir: "services/stock-price-ingestion"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stock-price-ingestion:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stock-price-ingestion:latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "stock-price-ingestion"
      - "--image"
      - "gcr.io/$PROJECT_ID/stock-price-ingestion:$COMMIT_SHA"
      - "--region"
      - "australia-southeast2"
      - "--platform"
      - "managed"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "600"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--concurrency"
      - "10"
      - "--set-env-vars"
      - "DATABASE_URL=$_DATABASE_URL,ENVIRONMENT=$_ENVIRONMENT,GCP_PROJECT=$PROJECT_ID"
      - "--service-account"
      - "stock-price-ingestion@$PROJECT_ID.iam.gserviceaccount.com"
      - "--allow-unauthenticated"

# Substitutions (set via Cloud Build trigger or command line)
substitutions:
  _DATABASE_URL: "postgresql://user:pass@host/db" # Override in trigger
  _ENVIRONMENT: "production"

# Build timeout
timeout: "1200s"

# Images to be pushed to Container Registry
images:
  - "gcr.io/$PROJECT_ID/stock-price-ingestion:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/stock-price-ingestion:latest"
