// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stocks/v1alpha1/stocks.proto
// Protobuf Java Version: 4.35.1

package com.stocks.v1alpha1;

@com.google.protobuf.Generated
public interface StockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stocks.v1alpha1.Stock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The stock code, e.g., "CBA", "ZIP", "PLS".
   * </pre>
   *
   * <code>string product_code = 1 [json_name = "productCode"];</code>
   * @return The productCode.
   */
  java.lang.String getProductCode();
  /**
   * <pre>
   * The stock code, e.g., "CBA", "ZIP", "PLS".
   * </pre>
   *
   * <code>string product_code = 1 [json_name = "productCode"];</code>
   * @return The bytes for productCode.
   */
  com.google.protobuf.ByteString
      getProductCodeBytes();

  /**
   * <pre>
   * The full name of the stock.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The full name of the stock.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>float total_product_in_issue = 3 [json_name = "totalProductInIssue"];</code>
   * @return The totalProductInIssue.
   */
  float getTotalProductInIssue();

  /**
   * <code>float reported_short_positions = 4 [json_name = "reportedShortPositions"];</code>
   * @return The reportedShortPositions.
   */
  float getReportedShortPositions();

  /**
   * <code>float percentage_shorted = 5 [json_name = "percentageShorted"];</code>
   * @return The percentageShorted.
   */
  float getPercentageShorted();

  /**
   * <code>string industry = 6 [json_name = "industry"];</code>
   * @return The industry.
   */
  java.lang.String getIndustry();
  /**
   * <code>string industry = 6 [json_name = "industry"];</code>
   * @return The bytes for industry.
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <code>repeated string tags = 7 [json_name = "tags"];</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 7 [json_name = "tags"];</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 7 [json_name = "tags"];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 7 [json_name = "tags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * TODO(castlemilk): add more metadata here as needed
   * </pre>
   *
   * <code>string logo_url = 8 [json_name = "logoUrl"];</code>
   * @return The logoUrl.
   */
  java.lang.String getLogoUrl();
  /**
   * <pre>
   * TODO(castlemilk): add more metadata here as needed
   * </pre>
   *
   * <code>string logo_url = 8 [json_name = "logoUrl"];</code>
   * @return The bytes for logoUrl.
   */
  com.google.protobuf.ByteString
      getLogoUrlBytes();
}
