version: 2

run:
  timeout: 5m
  issues-exit-code: 0 # Don't fail on linting issues for now
  tests: true
  skip-dirs:
    - gen
    - vendor
    - venv
    - node_modules
    - test/integration
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"
    - ".*_gen\\.go$"
    - ".*_connect\\.go$"

linters:
  enable:
    - govet # Vet examines Go source code (warnings only)
  disable-all: false
  fast: true # Run only fast linters

linters-settings:
  govet:
    check-shadowing: false

issues:
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
