apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    password: password
    database: shorts
    jsonData:
      postgresVersion: 1205
      sslMode: disable
    editable: true
