apiVersion: run.googleapis.com/v1
kind: Job 
metadata:
  name: shorts-data-sync
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: ${IMAGE_NAME}:${VERSION}
            command: python
            args:
              - main.py
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest 
                  name: DATABASE_URL