apiVersion: run.googleapis.com/v1
kind: Job 
metadata:
  name: shorts-data-sync
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: australia-southeast2-docker.pkg.dev/shorted-dev-aba5688f/shorted/short-data-sync:v0.2.2-45-g8373e2ed-dirty
            command: python
            args:
              - main.py
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest 
                  name: DATABASE_URL