apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shorts
spec:
  template:
    spec:
      containers:
      - image: australia-southeast2-docker.pkg.dev/shorted-dev-aba5688f/shorted/short-data-sync:v0.2.0-6-g5d099a8e-dirty
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: latest 
              name: DATABASE_URL