openapi: 3.1.0
info:
  x-logo:
    url: https://shorted.com.au/logo.png
paths:
  /register.v1.RegisterService/RegisterEmail:
    post:
      x-code-samples:
        - language: shell
          label: RegisterEmail
          source: |
            curl -X POST https://api.shorted.com.au/register.v1.RegisterService/RegisterEmail \
            -H "Content-Type: application/json" \
            -d '{"email": "user@example.com"}'
  /shorts.v1alpha1.ShortedStocksService/GetTopShorts:
    post:
      tags:
        - shorts.v1alpha1.ShortedStocksServicezzzzzz
